"""The 'pop' demo persona: a mainstream listener, taken seriously.

Nine weekly issues. Big pop, chart R&B, top-forty rap, stadium country and a
gym lane, with the shape a mainstream listener actually has: many plays, few
unique tracks, top artists carrying an enormous share.

The product angle, made visible in the picks: for this reader discovery is
one step sideways, not five. The album the hit came from. The writer behind
somebody else's song. The older record the current sound is copying.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from demo.author_lib import write  # noqa: E402

META = {
    "slug": "pop", "name": "Tasha",
    "persona": "Seven years of what was on, loved without irony and played on repeat.",
    "blurb": "Big pop, chart R&B, top-forty rap and stadium country, played in the car and at "
             "the gym. Many plays and few unique tracks, so every pick here is one step "
             "sideways rather than five.",
    "issue_count": 9, "first_date": "2026-06-20",
    "palette": ["#ff5d8f", "#ffb703", "#3a86ff", "#8338ec", "#fb5607"],
    "history": {"plays": 74300, "hours": 2184.0, "tracks": 9420, "artists": 2610,
                "window_start": "2019-03-02", "window_end": "2026-08-15"},
    "per_issue": {"singles": 5, "mixes": 2, "revivals": 3, "critics": 3, "releases": 5},
}

LANES = [
    ("big-pop", "Big Pop", 330,
     "The main room: stadium-scale pop albums played front to back and then again.",
     "active", 40, 612.4, ["Taylor Swift", "Dua Lipa", "Ariana Grande"],
     "The centre of everything for seven years, and still where most of the listening lands."),
    ("chart-rnb", "Chart R&B", 285,
     "Radio R&B and its slower cousins: the songs that carry a whole drive home.",
     "active", 34, 428.6, ["SZA", "Summer Walker", "Brent Faiyaz"],
     "Grew all summer, mostly at the sadder end and mostly late in the evening."),
    ("top-forty-rap", "Top Forty Rap", 65,
     "The rap that reaches the charts: hooks first, features everywhere.",
     "active", 38, 486.2, ["Drake", "Travis Scott", "Doja Cat"],
     "Steady and enormous, though the newer picks lean further from the singles than they used to."),
    ("stadium-country", "Stadium Country", 40,
     "Modern country built for arenas, plus the writers quietly doing the real work.",
     "rising", 26, 264.8, ["Kacey Musgraves", "Zach Bryan", "Chris Stapleton"],
     "The clearest riser in the record: barely present in the spring, unavoidable by August."),
    ("gym-hours", "Gym Hours", 145,
     "Music chosen entirely for tempo: hype rap, big house, anything that helps.",
     "active", 30, 342.7, ["David Guetta", "Megan Thee Stallion", "Calvin Harris"],
     "Perfectly steady, entirely functional, and the highest skip rate in the record by far."),
    ("sad-hours", "Sad Hours", 240,
     "The other functional lane: quiet pop for the end of a hard day.",
     "active", 28, 298.4, ["Billie Eilish", "Gracie Abrams", "Phoebe Bridgers"],
     "Rises and falls with the month rather than the year, which is the honest shape of it."),
    ("throwback-2000s", "Throwback", 200,
     "The pop of a childhood: nineties and two-thousands radio, played without apology.",
     "active", 32, 386.2, ["Britney Spears", "Usher", "Destiny's Child"],
     "Reliable comfort listening, and it spikes every time a new record disappoints."),
    ("latin-pop", "Latin Pop", 15,
     "Reggaeton and Latin pop, mostly through the crossover hits and increasingly past them.",
     "rising", 22, 186.4, ["Bad Bunny", "Karol G", "Rosalía"],
     "Rising fast, and the picks have started moving from the crossovers into the real thing."),
    ("kpop", "K-Pop", 305,
     "The most produced pop on earth, followed properly: b-sides, not just title tracks.",
     "dormant", 18, 148.6, ["NewJeans", "Twice"],
     "Went quiet after the spring, which happens when a favourite group stops releasing."),
    ("musicals", "Musicals", 95,
     "The personal outlier: cast recordings, inherited and known by heart.",
     "active", 12, 96.8, ["Original Broadway Cast", "Lin-Manuel Miranda"],
     "Small, constant, entirely unbothered by everything else in the record."),
]

ARTISTS = [
    ("Taylor Swift", 184.6, 3842, 0.11, "big-pop"),
    ("Dua Lipa", 82.4, 1684, 0.14, "big-pop"),
    ("Ariana Grande", 76.8, 1592, 0.16, "big-pop"),
    ("Harry Styles", 58.2, 1148, 0.13, "big-pop"),
    ("Olivia Rodrigo", 46.4, 968, 0.15, "big-pop"),
    ("Sabrina Carpenter", 38.6, 812, 0.18, "big-pop"),
    ("Chappell Roan", 32.4, 684, 0.17, "big-pop"),
    ("SZA", 68.4, 1342, 0.12, "chart-rnb"),
    ("Summer Walker", 42.6, 886, 0.19, "chart-rnb"),
    ("Brent Faiyaz", 36.8, 748, 0.16, "chart-rnb"),
    ("Frank Ocean", 44.2, 812, 0.09, "chart-rnb"),
    ("Giveon", 28.4, 596, 0.21, "chart-rnb"),
    ("Victoria Monet", 22.6, 468, 0.18, "chart-rnb"),
    ("Drake", 96.8, 2148, 0.24, "top-forty-rap"),
    ("Travis Scott", 62.4, 1386, 0.22, "top-forty-rap"),
    ("Doja Cat", 48.6, 1042, 0.20, "top-forty-rap"),
    ("Kendrick Lamar", 54.2, 1084, 0.14, "top-forty-rap"),
    ("Nicki Minaj", 38.4, 862, 0.26, "top-forty-rap"),
    ("Future", 34.6, 796, 0.28, "top-forty-rap"),
    ("Kacey Musgraves", 34.8, 682, 0.10, "stadium-country"),
    ("Zach Bryan", 42.6, 812, 0.13, "stadium-country"),
    ("Chris Stapleton", 28.4, 524, 0.11, "stadium-country"),
    ("Morgan Wallen", 36.2, 748, 0.19, "stadium-country"),
    ("Lainey Wilson", 18.6, 386, 0.16, "stadium-country"),
    ("David Guetta", 32.4, 812, 0.34, "gym-hours"),
    ("Megan Thee Stallion", 38.6, 924, 0.29, "gym-hours"),
    ("Calvin Harris", 34.2, 848, 0.31, "gym-hours"),
    ("Cardi B", 26.8, 648, 0.32, "gym-hours"),
    ("Lil Nas X", 22.4, 542, 0.28, "gym-hours"),
    ("Billie Eilish", 64.2, 1284, 0.10, "sad-hours"),
    ("Gracie Abrams", 32.6, 686, 0.14, "sad-hours"),
    ("Phoebe Bridgers", 28.4, 542, 0.12, "sad-hours"),
    ("Lana Del Rey", 46.8, 862, 0.15, "sad-hours"),
    ("Lorde", 34.2, 648, 0.13, "sad-hours"),
    ("Britney Spears", 42.6, 968, 0.17, "throwback-2000s"),
    ("Usher", 36.4, 824, 0.15, "throwback-2000s"),
    ("Destiny's Child", 28.8, 662, 0.14, "throwback-2000s"),
    ("Beyonce", 68.4, 1424, 0.12, "throwback-2000s"),
    ("Rihanna", 54.2, 1186, 0.16, "throwback-2000s"),
    ("Justin Timberlake", 24.6, 568, 0.22, "throwback-2000s"),
    ("Bad Bunny", 58.6, 1148, 0.18, "latin-pop"),
    ("Karol G", 34.2, 686, 0.20, "latin-pop"),
    ("Rosalía", 26.8, 512, 0.16, "latin-pop"),
    ("Peso Pluma", 18.4, 386, 0.24, "latin-pop"),
    ("NewJeans", 32.6, 748, 0.14, "kpop"),
    ("Twice", 24.8, 596, 0.18, "kpop"),
    ("Blackpink", 28.4, 662, 0.21, "kpop"),
    ("Stray Kids", 16.8, 412, 0.26, "kpop"),
    ("Original Broadway Cast", 42.6, 624, 0.08, "musicals"),
    ("Lin-Manuel Miranda", 28.4, 442, 0.07, "musicals"),
    ("Idina Menzel", 14.6, 268, 0.12, "musicals"),
    ("Ben Platt", 11.2, 214, 0.15, "musicals"),
]

ISSUES = [
    ("First Round", "Five songs from artists you have somehow never played, each one door away from something you play constantly."),
    ("Sideways Step", "The albums three of your favourite singles came from, which you have never opened."),
    ("Written For You", "Every pick this week was written or produced by someone behind a song you already love."),
    ("Long Way Home", "Country has taken over your summer, so this week follows it further in."),
    ("Loud Room", "Gym music with better bones, chosen for tempo and then for quality."),
    ("Quiet Car", "The slow end of pop, and one record that is quieter than anything you own."),
    ("Old Radio", "Two-thousands pop, plus the older records those songs were built out of."),
    ("Second Chance", "You skipped most of last issue, so this one stays closer to home."),
    ("Curtain Call", "Latin pop, a musical, and the best pop record of the year so far."),
]

ALBUMS = [
    ("Robyn", "Body Talk", 2010, "Konichiwa", "big-pop", "Dua Lipa", 8.7, False,
     "The record every crying-on-the-dancefloor song since has been trying to write, and it still outruns all of them."),
    ("Solange", "A Seat at the Table", 2016, "Saint", "chart-rnb", "SZA", 8.9, True,
     "Quiet, careful R&B about family and anger, and one of the best-sounding records of the decade."),
    ("Sade", "Love Deluxe", 1992, "Epic", "chart-rnb", "Frank Ocean", 9.0, False,
     "The most confident quiet record in pop, and the space in it is the whole point."),
    ("Kacey Musgraves", "Golden Hour", 2018, "MCA Nashville", "stadium-country", "Kacey Musgraves", 8.5, True,
     "Country that borrowed disco and daylight, and it won everything for good reason."),
    ("Jessie Ware", "What's Your Pleasure?", 2020, "PMR", "gym-hours", "Calvin Harris", 8.4, False,
     "A full disco record made with total conviction, and every song is a peak."),
    ("Cocteau Twins", "Heaven or Las Vegas", 1990, "4AD", "sad-hours", "Lana Del Rey", 9.1, False,
     "Vocals used as pure texture over guitars used as light, and it is genuinely soothing."),
    ("Janet Jackson", "The Velvet Rope", 1997, "Virgin", "throwback-2000s", "Beyonce", 8.6, False,
     "The most personal record a pop star made in the nineties, and the production still sounds current."),
    ("Rosalía", "El Mal Querer", 2018, "Columbia", "latin-pop", "Rosalía", 8.8, True,
     "Flamenco rebuilt as pop by someone who studied it properly, and it is thrillingly strange."),
    ("Carly Rae Jepsen", "Emotion", 2015, "604", "big-pop", "Sabrina Carpenter", 8.2, False,
     "The best pure pop album of its decade, ignored at the time and beloved ever since."),
]

CRITICS = [
    ("Mariah Carey", "Butterfly", 1997, 8.7, "rnb", "chart-rnb", False, "Ariana Grande",
     "The record where she stopped taking notes from anyone, and the singing is untouchable."),
    ("Miguel", "Kaleidoscope Dream", 2012, 8.6, "rnb", "chart-rnb", False, "Brent Faiyaz", None),
    ("Robyn", "Honey", 2018, 8.8, "pop", "big-pop", True, "Dua Lipa", None),
    ("Fleetwood Mac", "Rumours", 1977, 9.5, "rock", "throwback-2000s", False, "Taylor Swift",
     "The most-copied breakup album ever made, and every song is somebody's favourite."),
    ("Whitney Houston", "Whitney Houston", 1985, 8.4, "pop", "throwback-2000s", False, "Beyonce", None),
    ("Kelela", "Take Me Apart", 2017, 8.5, "rnb", "chart-rnb", False, "Victoria Monet", None),
    ("Shania Twain", "Come On Over", 1997, 8.3, "country", "stadium-country", False, "Lainey Wilson",
     "The best-selling country album in history, and it is a pure pop record wearing a hat."),
    ("Dolly Parton", "Jolene", 1974, 9.0, "country", "stadium-country", False, "Kacey Musgraves", None),
    ("Michael Jackson", "Off the Wall", 1979, 9.4, "pop", "throwback-2000s", False, "Usher",
     "Disco, funk and pop in one perfectly balanced hour, and nothing has bettered it."),
    ("Prince", "Sign o' the Times", 1987, 9.6, "pop", "throwback-2000s", False, "Justin Timberlake", None),
    ("Amy Winehouse", "Back to Black", 2006, 8.9, "rnb", "sad-hours", False, "Lana Del Rey",
     "Sixties soul arrangements behind the sharpest lyrics of the century so far."),
    ("Frank Ocean", "Channel Orange", 2012, 9.5, "rnb", "chart-rnb", True, "Frank Ocean", None),
    ("Lauryn Hill", "The Miseducation of Lauryn Hill", 1998, 9.4, "rnb", "top-forty-rap", False, "Doja Cat",
     "One album, no follow-up, and it still sets the bar for everyone who tries this."),
    ("Outkast", "Aquemini", 1998, 9.7, "rap", "top-forty-rap", False, "Kendrick Lamar", None),
    ("Missy Elliott", "Supa Dupa Fly", 1997, 8.8, "rap", "top-forty-rap", False, "Nicki Minaj",
     "Timbaland at his strangest behind the most charismatic rapper of the decade."),
    ("Kanye West", "Late Registration", 2005, 9.4, "rap", "top-forty-rap", False, "Drake", None),
    ("Madonna", "Ray of Light", 1998, 8.6, "pop", "big-pop", False, "Britney Spears",
     "A pop star at thirty-nine making the most forward record of her life."),
    ("ABBA", "The Visitors", 1981, 8.5, "pop", "big-pop", False, "Taylor Swift", None),
    ("Kate Bush", "Hounds of Love", 1985, 9.6, "pop", "sad-hours", False, "Billie Eilish",
     "Half perfect pop singles, half a suite about drowning, and both halves work."),
    ("Selena", "Amor Prohibido", 1994, 8.7, "latin", "latin-pop", False, "Karol G",
     "The record that made Tejano pop global, sung by someone who made it look effortless."),
    ("Buena Vista Social Club", "Buena Vista Social Club", 1997, 8.4, "latin", "latin-pop", False, "Bad Bunny", None),
    ("Daddy Yankee", "Barrio Fino", 2004, 8.2, "latin", "latin-pop", False, "Peso Pluma", None),
    ("Stevie Wonder", "Songs in the Key of Life", 1976, 9.8, "soul", "throwback-2000s", False, "Rihanna",
     "Two hours of a man at the peak of everything, and not one skippable song."),
    ("Donna Summer", "Bad Girls", 1979, 8.5, "disco", "gym-hours", False, "David Guetta", None),
    ("Daft Punk", "Discovery", 2001, 9.2, "electronic", "gym-hours", False, "Calvin Harris",
     "The house record that taught pop how to feel joyful, and it has not aged a day."),
    ("Jai Paul", "Leak 04-13", 2019, 8.6, "electronic", "gym-hours", False, "Megan Thee Stallion", None),
    ("Original Broadway Cast", "West Side Story", 1957, 9.0, "musical", "musicals", False, "Original Broadway Cast",
     "The score everyone quotes without knowing it, and the cast recording is still the best one."),
]

SINGLES = [
    # 001 First Round
    ("Tinashe", "Nasty", "chart-rnb", "SZA", None),
    ("Ravyn Lenae", "Love Me Not", "chart-rnb", "Summer Walker",
     "Chicago R&B with a voice light enough to float over anything"),
    ("Remi Wolf", "Photo ID", "big-pop", "Dua Lipa", None),
    ("Amaarae", "Angels in Tibet", "latin-pop", "Bad Bunny", None),
    ("Flo", "Cardboard Box", "chart-rnb", "Destiny's Child",
     "Three voices arranged the way girl groups were arranged in the nineties, on purpose"),
    # 002 Sideways Step
    ("Kali Uchis", "Moonlight", "latin-pop", "Karol G", None),
    ("Doechii", "Persuasive", "top-forty-rap", "Doja Cat", None),
    ("Snoh Aalegra", "I Want You Around", "chart-rnb", "Brent Faiyaz",
     "The slow one that everybody plays twice, and the strings do most of the work"),
    ("Lucky Daye", "Over", "chart-rnb", "Giveon", None),
    ("Muni Long", "Hrs and Hrs", "chart-rnb", "Victoria Monet", None),
    # 003 Written For You
    ("Julia Michaels", "Issues", "big-pop", "Olivia Rodrigo",
     "She wrote half the songs you already know, and this is the one she kept"),
    ("Tove Lo", "Habits", "big-pop", "Sabrina Carpenter", None),
    ("Caroline Polachek", "So Hot You're Hurting My Feelings", "big-pop", "Chappell Roan",
     "Pop with a strange voice at the centre of it, and the strangeness is the appeal"),
    ("Sofia Carson", "Hero", "big-pop", "Ariana Grande", None),
    ("Charli XCX", "Party 4 U", "gym-hours", "Dua Lipa", None),
    # 004 Long Way Home
    ("Sierra Ferrell", "In Dreams", "stadium-country", "Kacey Musgraves",
     "Old-time country sung by someone who actually rode the trains, and it shows"),
    ("Charley Crockett", "Welcome to Hard Times", "stadium-country", "Chris Stapleton", None),
    ("Tyler Childers", "Feathered Indians", "stadium-country", "Zach Bryan",
     "Kentucky songwriting with a voice that has no interest in being polished"),
    ("Margo Price", "Hurtin' on the Bottle", "stadium-country", "Lainey Wilson", None),
    ("Colter Wall", "Sleeping on the Blacktop", "stadium-country", "Morgan Wallen", None),
    # 005 Loud Room
    ("Fred again..", "Turn On the Lights again", "gym-hours", "Calvin Harris",
     "Built out of somebody's voice memo and it still fills a room completely"),
    ("Peggy Gou", "It Goes Like", "gym-hours", "David Guetta", None),
    ("Overmono", "So U Kno", "gym-hours", "Calvin Harris", None),
    ("Confidence Man", "Holiday", "gym-hours", "Lil Nas X", None),
    ("Latto", "Big Energy", "gym-hours", "Megan Thee Stallion", None),
    # 006 Quiet Car
    ("Faye Webster", "Kingston", "sad-hours", "Gracie Abrams",
     "Slide guitar under a pop song, sung like she is barely awake, and it is perfect"),
    ("Adrianne Lenker", "Anything", "sad-hours", "Phoebe Bridgers", None),
    ("Arlo Parks", "Eugene", "sad-hours", "Billie Eilish", None),
    ("Beabadoobee", "The Perfect Pair", "sad-hours", "Gracie Abrams", None),
    ("Clairo", "Sexy to Someone", "sad-hours", "Lorde",
     "Recorded to sound like an old record on purpose, and the songs hold up to it"),
    # 007 Old Radio
    ("Aaliyah", "Are You That Somebody", "throwback-2000s", "Usher",
     "The strangest drum programming ever to reach number one, and it still sounds like the future"),
    ("Brandy", "Full Moon", "throwback-2000s", "Beyonce", None),
    ("Craig David", "Fill Me In", "throwback-2000s", "Justin Timberlake", None),
    ("Blu Cantrell", "Hit 'Em Up Style", "throwback-2000s", "Rihanna", None),
    ("Amerie", "1 Thing", "throwback-2000s", "Britney Spears",
     "One drum break, one vocal, and one of the great singles of the decade"),
    # 008 Second Chance
    ("Victoria Monet", "On My Mama", "chart-rnb", "SZA", None),
    ("Coco Jones", "ICU", "chart-rnb", "Summer Walker", None),
    ("Tems", "Free Mind", "chart-rnb", "Frank Ocean",
     "A Nigerian voice with enormous patience, and the song never once rushes"),
    ("Ayra Starr", "Rush", "latin-pop", "Bad Bunny", None),
    ("Tyla", "Water", "chart-rnb", "Doja Cat", None),
    # 009 Curtain Call
    ("Feid", "Feliz Cumpleaños Ferxxo", "latin-pop", "Karol G", None),
    ("Young Miko", "Classy 101", "latin-pop", "Bad Bunny", None),
    ("Silvana Estrada", "Marchita", "latin-pop", "Rosalía",
     "One voice and one cuatro, recorded close, and it is completely disarming"),
    ("Original Broadway Cast", "Waitress", "musicals", "Original Broadway Cast", None),
    ("Jessie Reyez", "Figures", "chart-rnb", "SZA",
     "A voice that cracks on purpose, singing the meanest breakup song on the radio"),
]

MIXES = [
    ("BBC Radio 1", "Jack Saunders", "2026-06-13", "big-pop", 22, 8, "Dua Lipa", None),
    ("Apple Music 1", "Zane Lowe", "2026-06-17", "top-forty-rap", 20, 9, "Drake",
     "The interview show, but the records either side of the talking are the reason to stay"),
    ("BBC Radio 1", "Future Sounds", "2026-06-20", "big-pop", 24, 7, "Olivia Rodrigo", None),
    ("Apple Music Hits", "Nadeska", "2026-06-24", "chart-rnb", 18, 6, "SZA", None),
    ("BBC Radio 1", "Sian Eleri", "2026-06-27", "sad-hours", 16, 5, "Billie Eilish",
     "The late show, built for driving home, and it never once gets loud"),
    ("Apple Music Country", "Kelleigh Bannen", "2026-07-01", "stadium-country", 21, 8, "Kacey Musgraves", None),
    ("BBC Radio 1", "Danny Howard", "2026-07-04", "gym-hours", 26, 10, "Calvin Harris", None),
    ("Apple Music 1", "Ebro Darden", "2026-07-08", "top-forty-rap", 23, 11, "Travis Scott",
     "New York rap radio done properly, with actual opinions between the records"),
    ("BBC Radio 1", "Jamz Supernova", "2026-07-11", "chart-rnb", 19, 6, "Brent Faiyaz", None),
    ("Worldwide FM", "Tina Edwards", "2026-07-15", "chart-rnb", 17, 5, "Frank Ocean", None),
    ("Apple Music 1", "Travis Mills", "2026-07-18", "big-pop", 22, 9, "Harry Styles", None),
    ("BBC Radio 1", "Arielle Free", "2026-07-22", "gym-hours", 25, 9, "Peggy Gou" if False else "David Guetta", None),
    ("Apple Music Latin", "Ezra Sutton", "2026-07-25", "latin-pop", 20, 7, "Bad Bunny",
     "Two hours of reggaeton and its neighbours, sequenced by someone who loves all of it"),
    ("BBC Radio 1", "Charlie Hedges", "2026-07-29", "big-pop", 23, 8, "Ariana Grande", None),
    ("Apple Music Hits", "George Stroumboulopoulos", "2026-08-01", "throwback-2000s", 21, 10, "Beyonce",
     "An hour of two-thousands radio played by someone who was on the air the first time"),
    ("BBC Radio 1", "Vick Hope", "2026-08-05", "sad-hours", 18, 6, "Lana Del Rey", None),
    ("Apple Music 1", "Rebecca Judd", "2026-08-08", "kpop", 19, 6, "NewJeans", None),
    ("BBC Radio 1", "Jack Saunders", "2026-08-15", "stadium-country", 22, 7, "Zach Bryan", None),
]

REVIVALS = [
    ("Taylor Swift", "Cruel Summer", "Lover", 96, "2024-07-18", "big-pop",
     "Played more than any other song in your entire listening, and then nothing for a year"),
    ("Dua Lipa", "Levitating", "Future Nostalgia", 78, "2024-05-22", "big-pop", None),
    ("Ariana Grande", "positions", None, 64, "2024-03-14", "big-pop", None),
    ("SZA", "Kill Bill", "SOS", 82, "2024-08-04", "chart-rnb",
     "The song of one whole summer, worn completely smooth and then retired"),
    ("Summer Walker", "Girls Need Love", None, 52, "2024-04-08", "chart-rnb", None),
    ("Frank Ocean", "Pink + White", "Blonde", 58, "2024-06-26", "chart-rnb", None),
    ("Drake", "God's Plan", "Scorpion", 74, "2024-02-19", "top-forty-rap", None),
    ("Travis Scott", "Sicko Mode", "Astroworld", 68, "2024-07-02", "top-forty-rap",
     "The gym song for two straight years, and it stopped working all at once"),
    ("Doja Cat", "Say So", None, 56, "2023-12-11", "top-forty-rap", None),
    ("Kacey Musgraves", "Slow Burn", "Golden Hour", 42, "2024-05-16", "stadium-country", None),
    ("Zach Bryan", "Something in the Orange", None, 61, "2024-08-11", "stadium-country", None),
    ("Chris Stapleton", "Tennessee Whiskey", None, 46, "2024-03-28", "stadium-country", None),
    ("David Guetta", "Titanium", None, 54, "2023-11-20", "gym-hours", None),
    ("Megan Thee Stallion", "Savage", None, 62, "2024-06-10", "gym-hours", None),
    ("Calvin Harris", "Feels", None, 48, "2024-01-22", "gym-hours", None),
    ("Billie Eilish", "when the party's over", None, 66, "2024-04-24", "sad-hours",
     "A song for one specific kind of night, played through a whole year of them"),
    ("Gracie Abrams", "I miss you, I'm sorry", None, 44, "2024-02-06", "sad-hours", None),
    ("Lana Del Rey", "Mariners Apartment Complex", None, 38, "2024-07-26", "sad-hours", None),
    ("Britney Spears", "Toxic", None, 58, "2024-05-08", "throwback-2000s", None),
    ("Usher", "U Got It Bad", None, 41, "2023-12-28", "throwback-2000s", None),
    ("Beyonce", "Love on Top", None, 72, "2024-08-16", "throwback-2000s",
     "The key changes that used to get played on every good morning, and not once lately"),
    ("Rihanna", "Desperado", "Anti", 49, "2024-03-05", "throwback-2000s", None),
    ("Bad Bunny", "Tití Me Preguntó", None, 68, "2024-06-18", "latin-pop", None),
    ("Karol G", "Provenza", None, 51, "2024-04-30", "latin-pop", None),
    ("NewJeans", "Ditto", None, 47, "2024-05-28", "kpop",
     "Played constantly all spring and then dropped the moment the group went quiet"),
    ("Twice", "Feel Special", None, 34, "2024-01-16", "kpop", None),
    ("Original Broadway Cast", "Satisfied", "Hamilton", 39, "2024-07-14", "musicals", None),
]

RELEASES = [
    ("Taylor Swift", "The Tortured Poets Department Anthology", "album", "There will be nothing else on for a fortnight and that is fine."),
    ("SZA", "Lana", "album", None),
    ("Dua Lipa", "Radical Optimism Deluxe", "album", None),
    ("Sabrina Carpenter", "Short n' Sweet Deluxe", "album", "The deluxe has the two best songs on it, which is always the trick."),
    ("Chappell Roan", "The Giver", "single", None),
    ("Ariana Grande", "Eternal Sunshine Brighter Days", "album", None),
    ("Olivia Rodrigo", "Guts Spilled", "album", "Four extra songs and one of them is the best thing she has written."),
    ("Harry Styles", "Harry's House Live", "compilation", None),
    ("Billie Eilish", "Hit Me Hard and Soft Tour", "compilation", None),
    ("Gracie Abrams", "The Secret of Us Deluxe", "album", None),
    ("Phoebe Bridgers", "Punisher Anniversary", "compilation", "A reissue with demos, and the demos are somehow sadder."),
    ("Lana Del Rey", "Lasso", "album", "Her country record, which she has been promising for two years."),
    ("Lorde", "Virgin", "album", None),
    ("Frank Ocean", "Blonde Instrumentals", "compilation", None),
    ("Brent Faiyaz", "Larger Than Life Deluxe", "album", None),
    ("Summer Walker", "Finally Over It", "album", "The end of the trilogy, and the first two were both enormous."),
    ("Giveon", "Beloved", "album", None),
    ("Victoria Monet", "Jaguar III", "album", None),
    ("Drake", "For All the Dogs Scary Hours", "album", None),
    ("Travis Scott", "Jackboys 2", "compilation", "A posse album, which means the features do the heavy lifting."),
    ("Doja Cat", "Vie", "album", None),
    ("Kendrick Lamar", "GNX Deluxe", "album", "More from the record that took over last year."),
    ("Nicki Minaj", "Pink Friday 2 Gag City", "album", None),
    ("Future", "Mixtape Pluto", "album", None),
    ("Megan Thee Stallion", "Megan Act II", "album", None),
    ("Cardi B", "Am I the Drama", "album", "Seven years between albums, so expectations are absurd."),
    ("Calvin Harris", "Funk Wav Bounces Vol. 3", "album", None),
    ("David Guetta", "Future Rave II", "album", None),
    ("Lil Nas X", "Dreamboy", "album", None),
    ("Kacey Musgraves", "Deeper Well Deluxe", "album", "The quietest record she has made, and the deluxe leans further in."),
    ("Zach Bryan", "The Great American Bar Scene", "album", None),
    ("Chris Stapleton", "Higher Live", "compilation", None),
    ("Morgan Wallen", "One Thing at a Time Encore", "album", None),
    ("Lainey Wilson", "Whirlwind", "album", None),
    ("Bad Bunny", "Debí Tirar Más Fotos", "album", "A whole record about missing home, and it is his best in years."),
    ("Karol G", "Tropicoqueta", "album", None),
    ("Rosalía", "Lux", "album", "Recorded with an orchestra in thirteen languages, apparently."),
    ("Peso Pluma", "Exodo Deluxe", "album", None),
    ("NewJeans", "Supernatural", "single", "The first release since the group went quiet, so this matters."),
    ("Twice", "This Is For", "album", None),
    ("Blackpink", "Jump", "single", None),
    ("Stray Kids", "Karma", "album", None),
    ("Beyonce", "Cowboy Carter Act III", "album", "The last part of the trilogy, and the country one was extraordinary."),
    ("Rihanna", "R9", "album", None),
    ("Usher", "Coming Home Live", "compilation", None),
]

CATALOGS_POOL = [
    ("Taylor Swift", 148, 34, ["Cruel Summer", "All Too Well", "Style", "August"],
     [("Evermore", 2020), ("Speak Now Taylor's Version", 2023)],
     "The most-played artist in your listening by a mile, and two whole albums have never been opened."),
    ("Beyonce", 52, 44, ["Love on Top", "Formation", "Halo"],
     [("Cowboy Carter", 2024), ("4", 2011)],
     "You play the singles constantly and skip the albums, which she would take personally."),
    ("Drake", 86, 31, ["God's Plan", "Passionfruit", "Hotline Bling", "Nice for What"],
     [("Take Care", 2011), ("If You're Reading This It's Too Late", 2015)],
     "Hundreds of plays and the two records everyone agrees are his best are untouched."),
    ("SZA", 38, 48, ["Kill Bill", "Good Days", "Snooze"],
     [("Ctrl", 2017), ("SOS Deluxe", 2023)],
     "The songs from the album get played and the album never does."),
    ("Bad Bunny", 44, 42, ["Tití Me Preguntó", "Me Porto Bonito", "Moscow Mule"],
     [("YHLQMDLG", 2020), ("Un Verano Sin Ti Deluxe", 2022)],
     "One summer of singles, and the records they came from still sealed."),
    ("Billie Eilish", 46, 39, ["when the party's over", "Birds of a Feather", "Ocean Eyes"],
     [("Happier Than Ever", 2021), ("Hit Me Hard and Soft", 2024)],
     "You know every single and have never sat with either album end to end."),
]

if __name__ == "__main__":
    write(META, LANES, ARTISTS, ISSUES, ALBUMS, CRITICS, SINGLES, MIXES,
          REVIVALS, RELEASES, CATALOGS_POOL)
