"""The 'electronic' demo persona: a deep dance-music listener.

Thirteen weekly issues. Dub techno, UK bass, jungle, electro and ambient,
with the historical depth to match: this reader knows where all of it came
from and is still finding the corners.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from demo.author_lib import write  # noqa: E402

META = {
    "slug": "electronic", "name": "Mara",
    "persona": "Thirteen years of dance music, taken seriously and played loudly.",
    "blurb": "Dub techno, UK bass, jungle and ambient, with a record collector's sense of "
             "where all of it came from. Long sessions, low skips, and one lane that burned "
             "out completely in June.",
    "issue_count": 13, "first_date": "2026-05-23",
    "palette": ["#1b2a33", "#4a5a63", "#8f9ea3", "#c9d4d6", "#a8ff3e"],
    "history": {"plays": 121400, "hours": 4912.0, "tracks": 31200, "artists": 7840,
                "window_start": "2013-09-14", "window_end": "2026-08-15"},
    "per_issue": {"singles": 5, "mixes": 2, "revivals": 3, "critics": 3, "releases": 5},
}

LANES = [
    ("dub-chamber", "Dub Chamber", 190,
     "Dub techno and deep minimal: reverb as an instrument, chords used like weather.",
     "active", 38, 684.2, ["Rhythm & Sound", "Basic Channel", "Vladislav Delay"],
     "The steadiest room in the record all thirteen weeks, and the one the newer picks keep circling back to."),
    ("uk-bass", "UK Bass", 215,
     "Bass music from the island: garage, dubstep's deeper end, and whatever Bristol is calling it now.",
     "active", 40, 512.6, ["Pinch", "Peverelist", "Batu"],
     "Grew through early summer and now takes almost as much listening as the dub room."),
    ("jungle-dnb", "Jungle & Drum and Bass", 25,
     "Breakbeat science from ninety-three onward, amen breaks and Metalheadz weight.",
     "rising", 31, 388.4, ["Photek", "Source Direct", "Tim Reaper"],
     "Rising fast, mostly on the new jungle revival rather than the old records."),
    ("electro-braindance", "Electro & Braindance", 300,
     "Electro, Rephlex-adjacent melody and the machines that never sound quite human.",
     "active", 27, 276.8, ["Drexciya", "DMX Krew", "Ceephax Acid Crew"],
     "Held steady, with the acid end getting more attention than the melodic end lately."),
    ("ambient-drone", "Ambient & Drone", 240,
     "Long-form ambient and drone: the records that get put on and left on.",
     "active", 34, 431.5, ["Gas", "Stars of the Lid", "Ulla"],
     "Grew quietly, mostly at night and mostly as a way to come down from the club records."),
    ("club-deconstructed", "Deconstructed Club", 330,
     "Modern club music that has taken itself apart: unstable rhythm, no genre to sit in.",
     "rising", 22, 164.3, ["Objekt", "Toxe", "Air Max '97"],
     "The newest room and still filling, mostly from radio rather than from records."),
    ("house-lineage", "House Lineage", 45,
     "House traced back through Chicago and Detroit, plus the deep end of the modern version.",
     "active", 33, 342.7, ["Larry Heard", "Theo Parrish", "Kerri Chandler"],
     "Reliable and unhurried, the lane that never spikes and never dips."),
    ("techno-hard", "Hard Techno", 130,
     "The fast, loud, functional end: warehouse techno with nothing decorative left on it.",
     "burned", 29, 218.9, ["Surgeon", "Perc", "SPFDJ"],
     "Hammered through the spring and then dropped completely in June, which is the clearest break in the record."),
    ("breaks-hardcore", "Breaks & Hardcore", 90,
     "Hardcore continuum artefacts: breakbeat hardcore, rave stabs, happy accidents.",
     "dormant", 18, 97.4, ["Special Request", "Bizarre Inc"],
     "Went quiet after February and has only been touched a handful of times since."),
    ("dub-reggae", "Dub & Roots", 160,
     "The Jamaican source: King Tubby's mixing desk and the records that took it seriously.",
     "active", 21, 143.6, ["King Tubby", "Scientist", "Augustus Pablo"],
     "A small, personal room that grows a little every month and never gets skipped."),
]

ARTISTS = [
    ("Rhythm & Sound", 96.4, 1284, 0.05, "dub-chamber"),
    ("Basic Channel", 74.2, 942, 0.07, "dub-chamber"),
    ("Vladislav Delay", 41.8, 486, 0.11, "dub-chamber"),
    ("Deepchord", 38.6, 452, 0.08, "dub-chamber"),
    ("Yagya", 27.4, 341, 0.09, "dub-chamber"),
    ("Donato Dozzy", 33.2, 398, 0.13, "dub-chamber"),
    ("Fluxion", 22.7, 284, 0.10, "dub-chamber"),
    ("Pinch", 46.3, 812, 0.14, "uk-bass"),
    ("Peverelist", 39.8, 704, 0.11, "uk-bass"),
    ("Batu", 28.4, 512, 0.16, "uk-bass"),
    ("Kowton", 24.1, 438, 0.15, "uk-bass"),
    ("Hodge", 26.9, 486, 0.13, "uk-bass"),
    ("Loefah", 21.3, 372, 0.18, "uk-bass"),
    ("Mala", 31.6, 548, 0.09, "uk-bass"),
    ("Photek", 42.1, 594, 0.12, "jungle-dnb"),
    ("Source Direct", 28.7, 412, 0.14, "jungle-dnb"),
    ("Tim Reaper", 34.2, 618, 0.17, "jungle-dnb"),
    ("Dillinja", 26.4, 458, 0.16, "jungle-dnb"),
    ("Sully", 22.8, 396, 0.13, "jungle-dnb"),
    ("Goldie", 19.6, 268, 0.21, "jungle-dnb"),
    ("Drexciya", 36.8, 524, 0.10, "electro-braindance"),
    ("DMX Krew", 24.3, 428, 0.15, "electro-braindance"),
    ("Ceephax Acid Crew", 21.7, 384, 0.18, "electro-braindance"),
    ("Aphex Twin", 48.2, 782, 0.19, "electro-braindance"),
    ("Dopplereffekt", 16.4, 246, 0.22, "electro-braindance"),
    ("Gescom", 12.8, 194, 0.28, "electro-braindance"),
    ("Gas", 58.4, 386, 0.06, "ambient-drone"),
    ("Stars of the Lid", 44.6, 312, 0.04, "ambient-drone"),
    ("Ulla", 26.8, 298, 0.08, "ambient-drone"),
    ("Huerco S.", 31.2, 342, 0.09, "ambient-drone"),
    ("Thomas Köner", 22.4, 168, 0.12, "ambient-drone"),
    ("Eliane Radigue", 18.6, 96, 0.14, "ambient-drone"),
    ("Objekt", 27.6, 468, 0.16, "club-deconstructed"),
    ("Toxe", 14.2, 268, 0.24, "club-deconstructed"),
    ("Air Max '97", 12.6, 236, 0.26, "club-deconstructed"),
    ("Lorenzo Senni", 11.4, 214, 0.29, "club-deconstructed"),
    ("Yves Tumor", 9.8, 186, 0.31, "club-deconstructed"),
    ("Larry Heard", 41.6, 588, 0.07, "house-lineage"),
    ("Theo Parrish", 38.2, 462, 0.12, "house-lineage"),
    ("Kerri Chandler", 32.4, 484, 0.09, "house-lineage"),
    ("Moodymann", 29.8, 418, 0.11, "house-lineage"),
    ("Omar S", 24.6, 386, 0.15, "house-lineage"),
    ("DJ Sprinkles", 21.2, 214, 0.08, "house-lineage"),
    ("Surgeon", 34.8, 624, 0.18, "techno-hard"),
    ("Perc", 26.2, 482, 0.22, "techno-hard"),
    ("SPFDJ", 18.4, 348, 0.27, "techno-hard"),
    ("Blawan", 24.6, 452, 0.19, "techno-hard"),
    ("Randomer", 16.8, 312, 0.25, "techno-hard"),
    ("Special Request", 22.4, 386, 0.20, "breaks-hardcore"),
    ("Bizarre Inc", 11.6, 218, 0.26, "breaks-hardcore"),
    ("Luke Vibert", 14.8, 268, 0.23, "breaks-hardcore"),
    ("Tessela", 13.2, 242, 0.24, "breaks-hardcore"),
    ("2 Bad Mice", 9.4, 178, 0.28, "breaks-hardcore"),
    ("King Tubby", 31.4, 428, 0.04, "dub-reggae"),
    ("Scientist", 24.8, 342, 0.06, "dub-reggae"),
    ("Augustus Pablo", 22.6, 296, 0.05, "dub-reggae"),
    ("Lee Perry", 19.4, 268, 0.09, "dub-reggae"),
    ("Prince Jammy", 12.8, 178, 0.07, "dub-reggae"),
]

ISSUES = [
    ("Chain Reaction", "Thirteen weeks in and the dub room is still the centre of everything, so this week goes all the way in."),
    ("Amen Corner", "The jungle revival keeps getting better, and two of these came out this month."),
    ("Grey Water", "Bristol weight, mixed down until the low end is the only thing left."),
    ("Machine Language", "Electro from three continents, none of it trying to sound human."),
    ("Left Hand Path", "Deconstructed club and the sound of rhythm falling over on purpose."),
    ("Warehouse Ghost", "You stopped playing hard techno in June, so this is the version of it that survives."),
    ("Deep Water Mark", "Chicago and Detroit house, and the modern records that understood the assignment."),
    ("Kingston Rules", "Dub as an engineering practice, from the desk that invented it."),
    ("Slow Pressure", "An hour of ambient with a pulse in it, which is the only ambient you finish."),
    ("Second Frequency", "Half of last issue went unplayed, so this one is shorter and stranger."),
    ("Rave Artefact", "Hardcore fragments and the people still building out of them."),
    ("Signal Chain", "Records that sound like their own studio, from Basic Channel forward."),
    ("Night Ferry", "Closing the summer with the deep end of everything, and one record made in Iceland."),
]

ALBUMS = [
    ("Rhythm & Sound", "See Mi Yah", 2005, "Burial Mix", "dub-chamber", "Rhythm & Sound", 8.4, False,
     "One rhythm, ten singers, no variation permitted, and it is completely hypnotic."),
    ("Tim Reaper & Kloke", "In Full Effect", 2023, "Future Retro", "jungle-dnb", "Tim Reaper", 7.8, False,
     "Modern jungle made with total conviction, no irony anywhere in it."),
    ("Peverelist", "Tessellations", 2011, "Punch Drunk", "uk-bass", "Peverelist", 8.0, False,
     "Bristol techno built out of dubstep parts, and the drums never resolve where you expect."),
    ("Dopplereffekt", "Gesamtkunstwerk", 1999, "Gigolo", "electro-braindance", "Drexciya", 8.6, False,
     "Electro delivered like a physics lecture, cold enough to be genuinely funny."),
    ("Ulla", "Tumbling Towards a Wall", 2020, "Experiences Ltd", "ambient-drone", "Ulla", 8.2, False,
     "Ambient made of fragments that never quite lock together, and better for the gaps."),
    ("Objekt", "Cocoon Crush", 2018, "Pan", "club-deconstructed", "Objekt", 8.3, True,
     "Club music engineered to the millimetre and then bent out of shape on purpose."),
    ("Larry Heard", "Sceneries Not Songs, Volume One", 1994, "Black Market", "house-lineage", "Larry Heard", None, False,
     "Deep house at its most patient, made by the man who named the genre."),
    ("Scientist", "Scientist Rids the World of the Evil Curse of the Vampires", 1981, "Greensleeves", "dub-reggae", "Scientist", 9.0, False,
     "The best-titled record in dub and one of the best-mixed, which is a rare combination."),
    ("Stars of the Lid", "The Tired Sounds of Stars of the Lid", 2001, "Kranky", "ambient-drone", "Stars of the Lid", 9.1, False,
     "Two hours of guitar drone arranged like chamber music, and not one wasted minute."),
    ("Batu", "Opal", 2022, "Timedance", "uk-bass", "Batu", 7.7, False,
     "Bristol bass at its most abstract, with the swing still intact underneath."),
    ("Luke Vibert", "Big Soup", 1997, "Mo Wax", "breaks-hardcore", "Luke Vibert", None, False,
     "Breakbeats and jazz samples made by someone who clearly finds all of this hilarious."),
    ("Deepchord", "Vantage Isle Sessions", 2013, "Soma", "dub-chamber", "Deepchord", 7.6, False,
     "Detroit dub techno recorded like a field trip, all rain and distant chords."),
    ("Yagya", "Rigning", 2009, "Sending Orbs", "dub-chamber", "Yagya", None, False,
     "Icelandic dub techno named after rain, and it does sound exactly like that."),
]

CRITICS = [
    ("Basic Channel", "BCD", 1995, 9.4, "electronic", "dub-chamber", False, "Basic Channel",
     "The plates the whole lane descends from, and still the cleanest low end ever pressed."),
    ("Jeff Mills", "Waveform Transmission Vol. 1", 1992, 8.9, "electronic", "techno-hard", False, "Surgeon",
     "Detroit techno with nothing decorative left on it, and faster than most things made since."),
    ("Drexciya", "Neptune's Lair", 1999, 9.0, "electronic", "electro-braindance", False, "Drexciya", None),
    ("Photek", "Modus Operandi", 1997, 8.9, "electronic", "jungle-dnb", False, "Photek",
     "Drum and bass engineered like architecture, and the record that taught the genre restraint."),
    ("King Tubby", "King Tubby Meets Rockers Uptown", 1976, 9.3, "reggae", "dub-reggae", False, "Augustus Pablo",
     "The mixing desk as lead instrument, and the record every dub producer measures against."),
    ("Aphex Twin", "Selected Ambient Works 85-92", 1992, 9.5, "electronic", "ambient-drone", False, "Aphex Twin", None),
    ("Larry Heard", "Alien", 1996, 8.8, "electronic", "house-lineage", False, "Larry Heard", None),
    ("Autechre", "Incunabula", 1993, 8.6, "electronic", "electro-braindance", False, "Gescom",
     "The politest Autechre record, which makes it the one you can actually put on."),
    ("Goldie", "Timeless", 1995, 9.1, "electronic", "jungle-dnb", False, "Goldie", None),
    ("Theo Parrish", "Parallel Dimensions", 2000, 9.0, "electronic", "house-lineage", False, "Theo Parrish",
     "House mixed like a jazz record, deliberately rough, and it has aged into a classic."),
    ("Burial", "Untrue", 2007, 9.4, "electronic", "uk-bass", False, "Loefah", None),
    ("Wolfgang Voigt", "Gas", 1996, 8.7, "electronic", "ambient-drone", False, "Gas", None),
    ("Underground Resistance", "Revolution for Change", 1992, 8.8, "electronic", "techno-hard", False, "Perc",
     "Detroit techno as an actual political position, and the music backs it up."),
    ("Model 500", "Deep Space", 1995, 8.5, "electronic", "electro-braindance", False, "DMX Krew", None),
    ("Augustus Pablo", "East of the River Nile", 1978, 9.0, "reggae", "dub-reggae", False, "Lee Perry",
     "Melodica over dub plates, which should not work and turns out to be sublime."),
    ("Actress", "Hazyville", 2008, 8.4, "electronic", "club-deconstructed", False, "Objekt", None),
    ("Omni Trio", "The Deepest Cut Vol. 1", 1995, 8.6, "electronic", "jungle-dnb", False, "Dillinja", None),
    ("Ricardo Villalobos", "Alcachofa", 2003, 8.9, "electronic", "dub-chamber", False, "Fluxion",
     "Minimal house that keeps going long past where it should and earns every minute."),
    ("Moodymann", "Silentintroduction", 1997, 8.8, "electronic", "house-lineage", False, "Moodymann", None),
    ("Special Request", "Soul Music", 2013, 8.2, "electronic", "breaks-hardcore", False, "Special Request",
     "Pirate radio nostalgia made by someone who was actually there, which is why it stings."),
    ("Chain Reaction", "Various: We Are Reasonable People", 1998, 8.5, "electronic", "dub-chamber", False, "Vladislav Delay", None),
    ("Sully", "Escape", 2017, 7.9, "electronic", "jungle-dnb", False, "Sully", None),
    ("DJ Sprinkles", "Midtown 120 Blues", 2008, 9.0, "electronic", "house-lineage", True, "DJ Sprinkles",
     "Deep house with an essay attached, and both halves are essential."),
    ("Eliane Radigue", "Trilogie de la Mort", 1998, 8.8, "experimental", "ambient-drone", False, "Eliane Radigue", None),
    ("Pinch", "Underwater Dancehall", 2007, 7.8, "electronic", "uk-bass", False, "Pinch", None),
    ("Bizarre Inc", "Energique", 1992, 7.6, "electronic", "breaks-hardcore", False, "Bizarre Inc", None),
    ("Scientist", "Heavyweight Dub Champion", 1980, 8.9, "reggae", "dub-reggae", False, "Prince Jammy", None),
    ("Blawan", "Wet Will Always Dry", 2018, 8.0, "electronic", "techno-hard", False, "Blawan",
     "Techno made from sounds that should not be musical, arranged with total confidence."),
    ("Kerri Chandler", "Trionisphere", 2008, 8.1, "electronic", "house-lineage", False, "Kerri Chandler", None),
    ("Toxe", "Blinks", 2018, 7.5, "electronic", "club-deconstructed", False, "Toxe", None),
    ("Source Direct", "Controlled Developments", 1996, 8.3, "electronic", "jungle-dnb", False, "Source Direct", None),
    ("Thomas Köner", "Permafrost", 1993, 8.4, "experimental", "ambient-drone", False, "Thomas Köner",
     "Drone recorded as if from inside a glacier, and the most physically cold record here."),
    ("Mala", "Mala in Cuba", 2012, 7.9, "electronic", "uk-bass", False, "Mala", None),
    ("Ceephax Acid Crew", "United Acid Emirates", 2006, 7.7, "electronic", "electro-braindance", False, "Ceephax Acid Crew", None),
    ("Lee Perry", "Super Ape", 1976, 9.2, "reggae", "dub-reggae", False, "King Tubby",
     "The Black Ark at full strength, and the strangest-sounding great record in reggae."),
    ("Randomer", "Bring", 2019, 7.4, "electronic", "techno-hard", False, "Randomer", None),
    ("Huerco S.", "For Those of You Who Have Never (And Also Those Who Have)", 2016, 8.5, "electronic", "ambient-drone", True, "Huerco S.", None),
    ("Hodge", "Shadows in Blue", 2020, 7.8, "electronic", "uk-bass", False, "Hodge", None),
    ("Dillinja", "Cybotron", 1996, 8.2, "electronic", "jungle-dnb", False, "Tim Reaper", None),
]

SINGLES = [
    # 001 Chain Reaction
    ("Monolake", "Cyan", "dub-chamber", "Basic Channel", None),
    ("Porter Ricks", "Port Gentil", "dub-chamber", "Rhythm & Sound",
     "Hamburg dub techno that sounds like machinery in a flooded room"),
    ("Substance", "Relish", "dub-chamber", "Deepchord", None),
    ("Vainqueur", "Lyot", "dub-chamber", "Fluxion", None),
    ("Maurizio", "M4", "dub-chamber", "Basic Channel", None),
    # 002 Amen Corner
    ("Coco Bryce", "Won't Let Go", "jungle-dnb", "Tim Reaper", None),
    ("Dwarde", "Rush Hour", "jungle-dnb", "Sully", None),
    ("Sherelle", "Jungle Teknah", "jungle-dnb", "Tim Reaper", None),
    ("Nikki Nair", "Chopper", "club-deconstructed", "Objekt", None),
    ("Alix Perez", "Forsaken", "jungle-dnb", "Photek", None),
    # 003 Grey Water
    ("Ossia", "Vertigo", "uk-bass", "Peverelist",
     "Bristol dub weight at half speed, with more space in it than anything else here"),
    ("Bruce", "Not Stochastic", "uk-bass", "Batu", None),
    ("Ploy", "Ramos", "uk-bass", "Kowton", None),
    ("Facta", "Blush", "uk-bass", "Hodge", None),
    ("Lurka", "Beacon", "uk-bass", "Pinch", None),
    # 004 Machine Language
    ("Anthony Rother", "Sex With the Machines", "electro-braindance", "Drexciya", None),
    ("Umwelt", "Nyctalopia", "electro-braindance", "Dopplereffekt", None),
    ("Helena Hauff", "Sworn to Secrecy", "electro-braindance", "DMX Krew",
     "Hamburg electro played off hardware with the levels pushed too far, deliberately"),
    ("Jensen Interceptor", "Corrosive", "electro-braindance", "Ceephax Acid Crew", None),
    ("Silicon Scally", "Retina", "electro-braindance", "Aphex Twin", None),
    # 005 Left Hand Path
    ("Aya", "Emley Lights Us Moor", "club-deconstructed", "Toxe", None),
    ("Iceboy Violet", "Not So Sure", "club-deconstructed", "Air Max '97", None),
    ("Coucou Chloe", "Naughty Dog", "club-deconstructed", "Toxe", None),
    ("Jasss", "Turbo Rush", "club-deconstructed", "Objekt", None),
    ("Bergsonist", "Middle Ground", "club-deconstructed", "Lorenzo Senni", None),
    # 006 Warehouse Ghost
    ("Mark Broom", "Sound Surface", "techno-hard", "Surgeon", None),
    ("Regis", "Blood Witness", "techno-hard", "Perc",
     "Birmingham techno stripped to its bones, and the reverb is the only melody"),
    ("Ansome", "Stowaway", "techno-hard", "SPFDJ", None),
    ("Rhyw", "Fill Twelve", "techno-hard", "Blawan", None),
    ("Setaoc Mass", "Reflection", "techno-hard", "Randomer", None),
    # 007 Deep Water Mark
    ("Glenn Underground", "Sirius", "house-lineage", "Larry Heard", None),
    ("Chez Damier", "Can You Feel It", "house-lineage", "Kerri Chandler", None),
    ("Ron Trent", "Altered States", "house-lineage", "Theo Parrish",
     "Chicago house that runs eleven minutes and needs every one of them"),
    ("Boo Williams", "Mortal Thoughts", "house-lineage", "Omar S", None),
    ("Terrence Parker", "Love's Got Me High", "house-lineage", "Moodymann", None),
    # 008 Kingston Rules
    ("Errol Thompson", "Dub Fever", "dub-reggae", "King Tubby", None),
    ("Keith Hudson", "Blood Brothers", "dub-reggae", "Lee Perry",
     "The dark prince of dub, and this is the most haunted thing in the catalogue"),
    ("Yabby You", "Conquering Lion", "dub-reggae", "Augustus Pablo", None),
    ("Prince Far I", "Head of the Buffalo Soldier", "dub-reggae", "Scientist", None),
    ("Tommy McCook", "Rockers Almighty Dub", "dub-reggae", "Prince Jammy", None),
    # 009 Slow Pressure
    ("Voices from the Lake", "Silt", "dub-chamber", "Donato Dozzy",
     "Two producers building one seamless hour, and it never once announces itself"),
    ("Wolfgang Tillmans", "Device Control", "ambient-drone", "Gas", None),
    ("Kali Malone", "Sacer Boreas", "ambient-drone", "Eliane Radigue",
     "Pipe organ tuned to make the room itself resonate, and it is genuinely physical"),
    ("Sarah Davachi", "Chorus Scene", "ambient-drone", "Thomas Köner", None),
    ("Celer", "Vestiges of an Inheritance", "ambient-drone", "Stars of the Lid", None),
    # 010 Second Frequency
    ("Skee Mask", "Rev8617", "dub-chamber", "Vladislav Delay",
     "Breakbeats and grey ambience in the same track, from the most reliable producer in Munich"),
    ("Overmono", "Bby", "uk-bass", "Hodge", None),
    ("Anz", "You Could Be", "uk-bass", "Kowton", None),
    ("Pessimist", "Balance", "jungle-dnb", "Source Direct", None),
    ("Djrum", "Blue Violet", "ambient-drone", "Huerco S.",
     "Half ambient record and half drum workout, switching without warning and earning both"),
    # 011 Rave Artefact
    ("Sound of Fractures", "Tenacity", "breaks-hardcore", "Special Request", None),
    ("Nathan Fake", "The Sky Was Pink", "breaks-hardcore", "Luke Vibert", None),
    ("2 Bad Mice", "Bombscare", "breaks-hardcore", "Bizarre Inc",
     "The rave stab that launched a genre, still completely unhinged"),
    ("Sam Binga", "Wasted Days", "jungle-dnb", "Dillinja", None),
    ("Tessela", "Hackney Parrot", "breaks-hardcore", "Special Request", None),
    # 012 Signal Chain
    ("Shed", "The Traveller", "dub-chamber", "Yagya", None),
    ("Efdemin", "Decay", "dub-chamber", "Fluxion",
     "Techno recorded in a Japanese temple, and you can hear the room in every bar"),
    ("STL", "Silent State", "dub-chamber", "Deepchord", None),
    ("Sven Weisemann", "Xine", "house-lineage", "Larry Heard", None),
    ("Move D", "Beyond the Machine", "house-lineage", "DJ Sprinkles", None),
    # 013 Night Ferry
    ("Bjarki", "I Wanna Go Bang", "electro-braindance", "Aphex Twin", None),
    ("Rod Modell", "Captagon", "dub-chamber", "Deepchord",
     "Dub techno recorded in the wettest possible room, and the reverb never fully clears"),
    ("Kettel", "Cameltoe", "electro-braindance", "DMX Krew", None),
    ("Bvdub", "The First Day", "ambient-drone", "Gas",
     "One idea held for twenty minutes with total conviction, which is the whole appeal"),
    ("Andy Stott", "Numb", "dub-chamber", "Vladislav Delay", None),
]

MIXES = [
    ("NTS Radio", "Ben UFO", "2026-05-16", "uk-bass", 34, 11, "Peverelist",
     "The most trusted selector in the country, moving between decades without a seam"),
    ("Rinse FM", "Sherelle", "2026-05-20", "jungle-dnb", 38, 9, "Tim Reaper", None),
    ("NTS Radio", "Tim Reaper", "2026-05-27", "jungle-dnb", 41, 12, "Dillinja", None),
    ("Rinse FM", "Pinch", "2026-05-30", "uk-bass", 29, 10, "Pinch", None),
    ("NTS Radio", "Ossia", "2026-06-03", "uk-bass", 26, 7, "Loefah",
     "Bristol dub weight played at half speed, with room to breathe between every record"),
    ("The Lot Radio", "DJ Python", "2026-06-06", "dub-chamber", 22, 6, "Deepchord", None),
    ("NTS Radio", "Helena Hauff", "2026-06-10", "electro-braindance", 31, 8, "Drexciya", None),
    ("Rinse FM", "Objekt", "2026-06-13", "club-deconstructed", 27, 5, "Objekt",
     "A producer with perfect technical control choosing to make the mix feel unstable"),
    ("NTS Radio", "Aya", "2026-06-17", "club-deconstructed", 24, 4, "Toxe", None),
    ("Balamii", "Kessler", "2026-06-20", "techno-hard", 30, 9, "Blawan", None),
    ("NTS Radio", "Moodymann", "2026-06-24", "house-lineage", 25, 8, "Theo Parrish",
     "Detroit records played by the man who lives there, with all the talking left in"),
    ("Worldwide FM", "Bradley Zero", "2026-06-27", "house-lineage", 23, 7, "Kerri Chandler", None),
    ("NTS Radio", "Scientist", "2026-07-01", "dub-reggae", 20, 6, "King Tubby", None),
    ("Dublab", "Carlos Niño", "2026-07-04", "ambient-drone", 18, 5, "Stars of the Lid", None),
    ("NTS Radio", "Kali Malone", "2026-07-08", "ambient-drone", 14, 3, "Eliane Radigue",
     "A composer playing the drone records that taught her, which is the most useful kind of show"),
    ("Rinse FM", "Anz", "2026-07-11", "uk-bass", 33, 10, "Kowton", None),
    ("NTS Radio", "Skee Mask", "2026-07-15", "dub-chamber", 28, 7, "Vladislav Delay", None),
    ("Balamii", "Sam Binga", "2026-07-18", "jungle-dnb", 35, 11, "Sully", None),
    ("NTS Radio", "Special Request", "2026-07-22", "breaks-hardcore", 32, 9, "Special Request",
     "Pirate radio recreated by someone who was actually on it the first time"),
    ("Rinse FM", "Batu", "2026-07-25", "uk-bass", 26, 8, "Batu", None),
    ("NTS Radio", "Surgeon", "2026-07-29", "techno-hard", 29, 8, "Surgeon", None),
    ("The Lot Radio", "Eris Drew", "2026-08-01", "house-lineage", 21, 5, "Omar S", None),
    ("NTS Radio", "Donato Dozzy", "2026-08-05", "dub-chamber", 19, 6, "Donato Dozzy",
     "Two hours that move so slowly you stop noticing the transitions at all"),
    ("Rinse FM", "Hodge", "2026-08-08", "uk-bass", 31, 9, "Hodge", None),
    ("NTS Radio", "Nikki Nair", "2026-08-12", "club-deconstructed", 27, 6, "Air Max '97", None),
    ("Worldwide FM", "Peverelist", "2026-08-15", "uk-bass", 24, 8, "Peverelist", None),
]

REVIVALS = [
    ("Surgeon", "Krautrock", "Force + Form", 68, "2024-05-12", "techno-hard",
     "Played into the ground one spring and then dropped along with the whole lane"),
    ("Perc", "Dumpster", "The Power and the Glory", 54, "2024-03-08", "techno-hard", None),
    ("Blawan", "Getting Me Down", None, 47, "2023-11-19", "techno-hard", None),
    ("Basic Channel", "Phylyps Trak", None, 61, "2024-07-21", "dub-chamber", None),
    ("Rhythm & Sound", "Never Tell You", "With the Artists", 58, "2024-06-14", "dub-chamber",
     "One of the most-played things in the whole record, and silent for two years"),
    ("Vladislav Delay", "Kuula", "Multila", 43, "2024-02-25", "dub-chamber", None),
    ("Photek", "Ni Ten Ichi Ryu", "Modus Operandi", 52, "2024-04-16", "jungle-dnb",
     "The most-played drum pattern in your entire record, and untouched for two years"),
    ("Goldie", "Inner City Life", "Timeless", 39, "2023-12-03", "jungle-dnb", None),
    ("Dillinja", "The Angels Fell", None, 34, "2024-01-28", "jungle-dnb", None),
    ("Pinch", "Qawwali", None, 45, "2024-08-09", "uk-bass",
     "The dubstep track that still sounds like nothing else, and you stopped playing it"),
    ("Mala", "Changes", "Mala in Cuba", 37, "2024-05-26", "uk-bass", None),
    ("Loefah", "Mud", None, 41, "2023-10-15", "uk-bass", None),
    ("Drexciya", "Bubble Metropolis", None, 36, "2024-03-31", "electro-braindance", None),
    ("Aphex Twin", "Xtal", "Selected Ambient Works 85-92", 49, "2024-06-08", "electro-braindance",
     "Worn smooth from repetition and then set down completely"),
    ("DMX Krew", "You Can't Hide Your Love", None, 28, "2023-11-26", "electro-braindance", None),
    ("Gas", "Pop 1", "Pop", 44, "2024-07-14", "ambient-drone",
     "An hour-long track played twice a week for a year, and then not once since"),
    ("Stars of the Lid", "Requiem for Dying Mothers", None, 38, "2024-04-07", "ambient-drone",
     "Played on repeat through one difficult winter and not since it ended"),
    ("Huerco S.", "A Sea of Love", None, 31, "2024-02-11", "ambient-drone", None),
    ("Larry Heard", "Can You Feel It", None, 42, "2024-08-18", "house-lineage",
     "The record the whole lane rests on, and it has been sitting untouched for a year"),
    ("Theo Parrish", "Overyohead", None, 33, "2024-05-05", "house-lineage", None),
    ("Moodymann", "I Can't Kick This Feelin", None, 29, "2023-12-17", "house-lineage", None),
    ("Kerri Chandler", "Rain", None, 46, "2024-06-30", "house-lineage",
     "A deep house record about weather that got played through an entire wet spring"),
    ("King Tubby", "Dub Fi Gwan", None, 27, "2024-03-17", "dub-reggae", None),
    ("Scientist", "Your Teeth in My Neck", None, 32, "2024-07-28", "dub-reggae", None),
    ("Augustus Pablo", "King Tubby Meets Rockers Uptown", None, 35, "2024-01-14", "dub-reggae", None),
    ("Objekt", "Ganzfeld", None, 26, "2024-04-21", "club-deconstructed", None),
    ("Toxe", "Cinderella", None, 22, "2023-10-29", "club-deconstructed", None),
    ("Lorenzo Senni", "Elegant and Never Tiring", None, 24, "2024-02-04", "club-deconstructed", None),
    ("Special Request", "Lolita", None, 30, "2024-05-19", "breaks-hardcore",
     "Wore this out over one winter of late trains and has not gone back to it"),
    ("Luke Vibert", "Vibert Rides Again", None, 25, "2023-11-12", "breaks-hardcore", None),
    ("Bizarre Inc", "Playing With Knives", None, 21, "2024-01-07", "breaks-hardcore", None),
    ("Tim Reaper", "Metallic Rain", None, 40, "2024-08-04", "jungle-dnb",
     "Played constantly while the jungle habit was forming, then dropped once it settled"),
    ("Sully", "Swandive", None, 23, "2024-03-24", "jungle-dnb", None),
    ("Batu", "Marlow", None, 28, "2024-06-16", "uk-bass", None),
    ("Peverelist", "Roll With the Punches", None, 37, "2024-07-07", "uk-bass",
     "Bristol drums at their most patient, and a track you used to open everything with"),
    ("Kowton", "Shuffle Good", None, 26, "2024-02-18", "uk-bass", None),
    ("Deepchord", "Vantage Isle", None, 33, "2024-05-12", "dub-chamber", None),
    ("Yagya", "Snowflake 1", None, 29, "2024-04-28", "dub-chamber", None),
    ("Donato Dozzy", "Menta", None, 31, "2024-08-11", "dub-chamber", None),
]

RELEASES = [
    ("Objekt", "Chalk Line", "single", "Objekt releases rarely and it is always worth stopping for."),
    ("Batu", "Inertia", "ep", "Timedance runs on records like this: swing first, everything else second."),
    ("Tim Reaper", "Cosmic Void", "album", "A full jungle album rather than a plate, which he almost never does."),
    ("Peverelist", "Pulse X Series", "ep", None),
    ("Vladislav Delay", "Rakka III", "album", "Uploaded without warning, as always, and worth clearing an evening for."),
    ("Hodge", "Lucid Bloom", "album", "Bristol techno with the low end doing all the melodic work."),
    ("Kowton", "Loos in Twos", "ep", None),
    ("Huerco S.", "Plonk II", "album", "The follow-up to the record that changed what ambient could sound like."),
    ("Ulla", "Foam", "album", "Ambient assembled from offcuts, and the seams are the best part."),
    ("Eliane Radigue", "All Life Long", "album", None),
    ("Thomas Köner", "The Head as Form'd in the Crier's Choir", "album", None),
    ("Larry Heard", "Cerebral Hemispheres II", "album", "Still recording, still unhurried, still ahead of everyone."),
    ("Theo Parrish", "DJ-Kicks", "compilation", "A mix rather than a record, and he sequences like nobody else alive."),
    ("Moodymann", "Taken Away II", "album", "Detroit house with the talking left in, which is the whole charm."),
    ("Kerri Chandler", "Spaces and Places Vol. 2", "album", "The last volume was recorded in a different club every night."),
    ("Omar S", "Can't Change", "album", None),
    ("DJ Sprinkles", "Gayest Tits", "compilation", None),
    ("Surgeon", "Crash Recoil", "album", "A lane you burned out on, from the one artist who might pull you back."),
    ("Blawan", "Dismantled Into Juice", "ep", "Drums made from sounds that should not be musical at all."),
    ("SPFDJ", "Intrepid Skin", "ep", None),
    ("Perc", "The Cut Off", "album", None),
    ("Special Request", "Offworld", "album", "Four albums in one year last time, so brace for volume."),
    ("Luke Vibert", "Modern Rave", "album", None),
    ("Drexciya", "Journey of the Deep Sea Dweller", "compilation", "A proper reissue of the plates, finally mastered kindly."),
    ("Aphex Twin", "Blackbox Life Recorder", "ep", "Still finding new corners in the same machines after all this time."),
    ("DMX Krew", "Loose Gears", "album", "Electro played on hardware with the warmth left in."),
    ("Ceephax Acid Crew", "Camelot", "album", None),
    ("Dopplereffekt", "Neurotelepathy", "album", "Cold enough to be funny, which is the trick they never lose."),
    ("Rhythm & Sound", "See Mi Yah Remixes", "compilation", None),
    ("Basic Channel", "Quadrant Dub Reissue", "compilation", "The dub versions on their own, which is how these were meant to be heard."),
    ("Vladislav Delay", "Multila Reissue", "compilation", None),
    ("Deepchord", "Functional Extraits", "ep", None),
    ("Yagya", "Sleepygirls", "album", None),
    ("Donato Dozzy", "Magda", "album", None),
    ("Fluxion", "Perspectives", "album", "Dub techno from the quiet end of the Chain Reaction family."),
    ("Pinch", "Reality Tunnels", "album", "His first solo record in years, and the sub bass is still the point."),
    ("Mala", "Mirrors II", "album", "Sub bass recorded in another country again, which always suits him."),
    ("Loefah", "Swamp Archive", "compilation", None),
    ("Kowton", "Utility II", "album", None),
    ("Sully", "Blue", "ep", "Jungle with a garage swing under it, and the drums are immaculate."),
    ("Photek", "Form & Function Vol. 3", "album", "The third volume of remixes, and the first two are canon."),
    ("Source Direct", "Exorcise the Demons II", "album", None),
    ("Dillinja", "Valve Sound System Archive", "compilation", None),
    ("Goldie", "The Journey Man II", "album", "Orchestral drum and bass, which he has always taken more seriously than anyone."),
    ("Toxe", "Vanity Project", "ep", "Club music that keeps dissolving before the drop, deliberately."),
    ("Air Max '97", "Horizon Scanning", "album", None),
    ("Lorenzo Senni", "Canone Infinito II", "album", None),
    ("Yves Tumor", "Praise a Lord Who Bleeds", "album", None),
    ("King Tubby", "Dub From the Roots Reissue", "compilation", "Remastered from the original tapes for the first time."),
    ("Scientist", "Dub in the Roots Tradition", "compilation", "The desk work that every producer in your listening is still copying."),
    ("Augustus Pablo", "Rockers Meets King Tubbys", "compilation", None),
    ("Lee Perry", "Black Ark Archives", "compilation", None),
    ("Prince Jammy", "Kamikaze Dub Reissue", "compilation", None),
    ("Bizarre Inc", "Rave Archive", "compilation", None),
    ("Randomer", "Bring II", "ep", None),
    ("Gas", "Rausch Reissue", "compilation", "The first proper reissue of the densest record in the catalogue."),
    ("Stars of the Lid", "Gasoline Age Reissue", "compilation", "Guitar drone arranged like chamber music, back in print at last."),
    ("Thomas Köner", "Motus", "album", None),
    ("Eliane Radigue", "Occam Ocean Vol. 5", "album", None),
    ("Gescom", "Minidisc Reissue", "compilation", None),
    ("Objekt", "Split Tape", "ep", None),
    ("Toxe", "A World of Service", "album", None),
    ("Peverelist", "Devil's Dance", "album", "The Bristol dub record everyone has been waiting on."),
    ("Batu", "Sonder Contour", "album", None),
    ("Hodge", "Blush II", "album", None),
]

CATALOGS_POOL = [
    ("Basic Channel", 12, 62, ["Phylyps Trak", "Q1.1", "Octagon"],
     [("BCD-2", 2008), ("Radiance", 1995)],
     "A catalogue of twelve records total, and you have somehow only played half of them."),
    ("King Tubby", 28, 48, ["Dub Fi Gwan", "King Tubby Meets Rockers Uptown", "A Rougher Version"],
     [("Dub Gone Crazy", 1981), ("The Roots of Dub", 1975)],
     "The most important engineer in music, and the albums under his own name are unopened."),
    ("Larry Heard", 34, 41, ["Can You Feel It", "Mystery of Love", "Washing Machine"],
     [("Sceneries Not Songs Vol. 2", 1996), ("Genesis", 1999)],
     "The hits get played constantly and the ambient records he loves most get skipped."),
    ("Aphex Twin", 47, 38, ["Xtal", "Windowlicker", "Avril 14th", "Rhubarb"],
     [("Drukqs", 2001), ("Syro", 2014)],
     "An enormous catalogue reduced to the four tracks everyone knows, which is a waste."),
    ("Photek", 22, 53, ["Ni Ten Ichi Ryu", "The Hidden Camera", "Rings Around Saturn"],
     [("Solaris", 2000), ("Ku:Palm", 2012)],
     "Two albums heard and three never opened, and the unheard ones are the strange ones."),
    ("Theo Parrish", 39, 36, ["Overyohead", "Falling Up", "Synthetic Flemm"],
     [("American Intelligence", 2014), ("Sound Sculptures Vol. 1", 2007)],
     "You play the twelve-inches and never the albums, which is where he actually stretches out."),
    ("Gas", 9, 71, ["Pop 1", "Pop 2", "Zauberberg I"],
     [("Narkopop", 2017), ("Der Lange Marsch", 2021)],
     "Nine long tracks in your listening and the two most recent records untouched."),
    ("Surgeon", 31, 44, ["Krautrock", "Bad Hands", "Presents Dynamic Tension"],
     [("Force + Form", 1999), ("Breaking the Frame", 2016)],
     "A lane you burned out on, with the two best records in it never played once."),
]

if __name__ == "__main__":
    write(META, LANES, ARTISTS, ISSUES, ALBUMS, CRITICS, SINGLES, MIXES,
          REVIVALS, RELEASES, CATALOGS_POOL)
