"""The 'altindie' demo persona: a deep alternative and indie listener.

Eleven weekly issues. Post-punk, shoegaze, slowcore, nineties indie and the
songwriters underneath it all, with the long memory to know the lineage.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from demo.author_lib import write  # noqa: E402

META = {
    "slug": "altindie", "name": "June",
    "persona": "Twelve years of records, mostly guitars, always the whole album.",
    "blurb": "Post-punk, shoegaze, slowcore and the songwriters underneath all of it, played "
             "start to finish rather than shuffled. One lane went quiet in July and a folk "
             "habit grew into the gap.",
    "issue_count": 11, "first_date": "2026-06-06",
    "palette": ["#c9a7a0", "#8a9a7b", "#e8e2d5", "#3f4a58", "#b5713f"],
    "history": {"plays": 96200, "hours": 3452.0, "tracks": 27400, "artists": 9140,
                "window_start": "2014-06-21", "window_end": "2026-08-15"},
    "per_issue": {"singles": 5, "mixes": 2, "revivals": 3, "critics": 3, "releases": 5},
}

LANES = [
    ("post-punk", "Post-Punk", 20,
     "Angular guitars and spoken threat, from the first wave through whatever London is doing now.",
     "active", 40, 486.3, ["Television", "Wire", "Dry Cleaning"],
     "The anchor lane, steady through all eleven weeks and still taking new names every issue."),
    ("shoegaze-dream", "Shoegaze & Dream Pop", 265,
     "Guitars as weather: reverb, tremolo and vocals used as another layer of texture.",
     "active", 38, 412.7, ["My Bloody Valentine", "Slowdive", "Cocteau Twins"],
     "Grew all summer on the back of the reissue campaigns and the newer bands copying them."),
    ("slowcore", "Slowcore", 210,
     "Quiet, slow, deliberate music where the silence between notes is the instrument.",
     "active", 26, 268.4, ["Low", "Codeine", "Duster"],
     "Small but immovable, and the lane with the lowest skip rate in the whole record."),
    ("nineties-indie", "Nineties Indie", 45,
     "American indie rock from the Pavement decade: loose, tuneful, allergic to polish.",
     "active", 40, 524.8, ["Pavement", "Yo La Tengo", "Built to Spill"],
     "The biggest lane by hours, and the one most likely to be playing on a weekday."),
    ("art-pop", "Art Pop", 310,
     "Pop structures pulled out of shape: studio-built, unafraid of prettiness.",
     "rising", 24, 196.5, ["Kate Bush", "Talk Talk", "Weyes Blood"],
     "Rising steadily, mostly through the older records rather than the current ones."),
    ("folk-edges", "Folk & Its Edges", 90,
     "British and American folk, plus the stranger corners: private press, drone folk, freak folk.",
     "rising", 22, 174.2, ["Vashti Bunyan", "Bert Jansch", "Bill Fay"],
     "The newest habit in the record, and it has grown every single week since July."),
    ("noise-math", "Noise & Math Rock", 130,
     "Loud, technical, unsentimental: guitars used as percussion and time signatures as jokes.",
     "dormant", 19, 142.6, ["Slint", "Shellac", "Hella"],
     "Went quiet in July after two years of steady listening, with no obvious reason."),
    ("americana", "Americana", 65,
     "Country-adjacent songwriting by people who came to it sideways.",
     "active", 21, 158.9, ["Lucinda Williams", "Jason Molina", "Big Thief"],
     "Reliable and growing slowly, mostly late at night and mostly the sadder end."),
    ("ambient-retreat", "Ambient Retreat", 240,
     "The room this reader goes to when guitars are too much: minimal, patient, wordless.",
     "active", 18, 128.4, ["Brian Eno", "Grouper", "Hiroshi Yoshimura"],
     "A small retreat that gets used most in the weeks the loud lanes get heavy rotation."),
    ("soul-corner", "Soul Corner", 350,
     "The personal outlier: sixties and seventies soul inherited and never let go of.",
     "active", 16, 112.7, ["Bill Withers", "Curtis Mayfield", "Ann Peebles"],
     "Never large and never absent, the lane that proves this is a person and not a genre chart."),
]

ARTISTS = [
    ("Television", 42.6, 618, 0.06, "post-punk"),
    ("Wire", 34.8, 682, 0.11, "post-punk"),
    ("Dry Cleaning", 28.4, 496, 0.13, "post-punk"),
    ("The Fall", 38.2, 742, 0.19, "post-punk"),
    ("Gang of Four", 24.6, 448, 0.12, "post-punk"),
    ("Protomartyr", 21.8, 386, 0.14, "post-punk"),
    ("bar italia", 18.4, 342, 0.16, "post-punk"),
    ("Squid", 16.2, 294, 0.18, "post-punk"),
    ("My Bloody Valentine", 44.8, 624, 0.08, "shoegaze-dream"),
    ("Slowdive", 39.2, 548, 0.05, "shoegaze-dream"),
    ("Cocteau Twins", 32.6, 486, 0.07, "shoegaze-dream"),
    ("Ride", 22.4, 384, 0.13, "shoegaze-dream"),
    ("Wednesday", 19.6, 348, 0.15, "shoegaze-dream"),
    ("Beach House", 36.4, 562, 0.09, "shoegaze-dream"),
    ("Duster", 26.8, 512, 0.06, "slowcore"),
    ("Low", 34.2, 486, 0.05, "slowcore"),
    ("Codeine", 18.6, 268, 0.07, "slowcore"),
    ("Red House Painters", 24.4, 312, 0.06, "slowcore"),
    ("Grouper", 21.2, 264, 0.04, "ambient-retreat"),
    ("Pavement", 48.6, 862, 0.10, "nineties-indie"),
    ("Yo La Tengo", 41.2, 668, 0.08, "nineties-indie"),
    ("Built to Spill", 28.6, 468, 0.11, "nineties-indie"),
    ("Dinosaur Jr.", 26.4, 442, 0.14, "nineties-indie"),
    ("Guided by Voices", 22.8, 596, 0.22, "nineties-indie"),
    ("Sonic Youth", 34.6, 524, 0.16, "nineties-indie"),
    ("Modest Mouse", 24.2, 418, 0.15, "nineties-indie"),
    ("Kate Bush", 31.4, 452, 0.08, "art-pop"),
    ("Talk Talk", 27.8, 286, 0.05, "art-pop"),
    ("Weyes Blood", 19.4, 312, 0.09, "art-pop"),
    ("Julia Holter", 16.8, 248, 0.12, "art-pop"),
    ("Broadcast", 18.2, 296, 0.10, "art-pop"),
    ("Vashti Bunyan", 12.6, 184, 0.06, "folk-edges"),
    ("Bert Jansch", 16.4, 242, 0.09, "folk-edges"),
    ("Bill Fay", 11.8, 168, 0.05, "folk-edges"),
    ("Nick Drake", 22.6, 342, 0.04, "folk-edges"),
    ("Linda Perhacs", 8.4, 124, 0.07, "folk-edges"),
    ("Slint", 21.4, 268, 0.09, "noise-math"),
    ("Shellac", 16.8, 284, 0.15, "noise-math"),
    ("Hella", 9.6, 176, 0.24, "noise-math"),
    ("Don Caballero", 12.4, 208, 0.18, "noise-math"),
    ("Unwound", 14.8, 262, 0.16, "noise-math"),
    ("Lucinda Williams", 18.6, 268, 0.07, "americana"),
    ("Jason Molina", 24.8, 386, 0.06, "americana"),
    ("Big Thief", 32.4, 512, 0.08, "americana"),
    ("Bonnie Prince Billy", 19.2, 296, 0.11, "americana"),
    ("Gillian Welch", 14.6, 208, 0.05, "americana"),
    ("Brian Eno", 26.2, 312, 0.07, "ambient-retreat"),
    ("Hiroshi Yoshimura", 14.8, 168, 0.03, "ambient-retreat"),
    ("Harold Budd", 12.4, 142, 0.05, "ambient-retreat"),
    ("Bill Withers", 22.8, 386, 0.04, "soul-corner"),
    ("Curtis Mayfield", 19.6, 312, 0.06, "soul-corner"),
    ("Ann Peebles", 11.4, 196, 0.08, "soul-corner"),
    ("Bobby Womack", 13.2, 214, 0.09, "soul-corner"),
]

ISSUES = [
    ("Coil and Spring", "Post-punk from three decades, and the newest one is the loudest."),
    ("Blue Weather", "Guitars used as weather, mostly from the years when that was a new idea."),
    ("Whole Rooms Quiet", "The slowest week yet on purpose, with nothing on it above a certain volume."),
    ("Loose Change", "Nineties indie by bands who were allergic to sounding expensive."),
    ("Kitchen Radio", "Art pop and studio records that took prettiness seriously."),
    ("Field Recording", "The folk habit that keeps growing, traced back to where it came from."),
    ("Hard Angles", "You stopped playing math rock in July, so this is a case for going back."),
    ("Long Drive", "Country-adjacent songwriting, and every one of these is about leaving."),
    ("Small Hours", "Ambient and almost-ambient, for the weeks when guitars are too much."),
    ("Second Look", "Most of last issue went unplayed, so this one is warmer and shorter."),
    ("Late Summer", "Closing out with soul records, folk records, and one that is both."),
]

ALBUMS = [
    ("Television", "Adventure", 1978, "Elektra", "post-punk", "Television", 8.4, False,
     "The second record, quieter and stranger than the first, and unfairly ignored for fifty years."),
    ("Slowdive", "Pygmalion", 1995, "Creation", "shoegaze-dream", "Slowdive", 8.8, False,
     "The band dissolving their own sound into almost nothing, and it is the best thing they made."),
    ("Codeine", "The White Birch", 1994, "Sub Pop", "slowcore", "Codeine", 8.6, False,
     "Slowcore at its most severe, with every note given far more room than seems wise."),
    ("Yo La Tengo", "And Then Nothing Turned Itself Inside-Out", 2000, "Matador", "nineties-indie", "Yo La Tengo", 9.0, False,
     "A whispered record about a long marriage, and the warmest thing in their catalogue."),
    ("Talk Talk", "Spirit of Eden", 1988, "Parlophone", "art-pop", "Talk Talk", 9.3, False,
     "A pop band spending a fortune to make something almost silent, and getting away with it."),
    ("Bill Fay", "Time of the Last Persecution", 1971, "Deram", "folk-edges", "Bill Fay", 8.7, False,
     "English folk with a jazz band behind it and the end of the world in the lyrics."),
    ("Unwound", "Leaves Turn Inside You", 2001, "Kill Rock Stars", "noise-math", "Unwound", 9.1, False,
     "A noise band making their double album and finding real beauty in it before breaking up."),
    ("Jason Molina", "Pyramid Electric Co.", 2004, "Secretly Canadian", "americana", "Jason Molina", 7.9, False,
     "One voice, one piano, one room, and almost too much honesty to sit through."),
    ("Hiroshi Yoshimura", "Green", 1986, "Air Records", "ambient-retreat", "Hiroshi Yoshimura", 8.6, False,
     "Japanese environmental music written for a house rather than a stage, and it works perfectly."),
    ("Wednesday", "Rat Saw God", 2023, "Dead Oceans", "shoegaze-dream", "Wednesday", 8.5, True,
     "Country songs played through shoegaze amps, sung by the best young lyricist in the format."),
    ("Ann Peebles", "I Can't Stand the Rain", 1974, "Hi Records", "soul-corner", "Ann Peebles", None, False,
     "Memphis soul with the tightest rhythm section on earth and a voice that never oversells."),
]

CRITICS = [
    ("Television", "Marquee Moon", 1977, 10.0, "rock", "post-punk", False, "Television",
     "The record that made guitars conversational, and the reason half this lane exists."),
    ("The Feelies", "Crazy Rhythms", 1980, 9.2, "rock", "post-punk", False, "Wire", None),
    ("Galaxie 500", "On Fire", 1989, 9.1, "rock", "shoegaze-dream", False, "Slowdive",
     "Three people playing as slowly and simply as possible, and it aches."),
    ("Slint", "Spiderland", 1991, 9.4, "rock", "noise-math", False, "Slint", None),
    ("Talk Talk", "Laughing Stock", 1991, 9.5, "rock", "art-pop", False, "Talk Talk",
     "The furthest a pop band has ever travelled from pop, recorded in near darkness."),
    ("Vashti Bunyan", "Just Another Diamond Day", 1970, 8.7, "folk", "folk-edges", False, "Vashti Bunyan", None),
    ("Karate", "Some Boots", 2002, 8.2, "rock", "slowcore", False, "Codeine", None),
    ("Sibylle Baier", "Colour Green", 2006, 8.4, "folk", "folk-edges", False, "Linda Perhacs",
     "Recorded at home in the seventies, found thirty years later, and completely intact."),
    ("Bill Withers", "Live at Carnegie Hall", 1973, 9.3, "soul", "soul-corner", False, "Bill Withers", None),
    ("Low", "Things We Lost in the Fire", 2001, 9.0, "rock", "slowcore", False, "Low",
     "The quietest band in America learning to use a studio, and losing none of the restraint."),
    ("Kate Bush", "Hounds of Love", 1985, 9.6, "pop", "art-pop", False, "Kate Bush", None),
    ("Pavement", "Wowee Zowee", 1995, 9.2, "rock", "nineties-indie", False, "Pavement",
     "The sprawling one, which is the one that keeps rewarding you twenty years later."),
    ("Nick Drake", "Pink Moon", 1972, 9.2, "folk", "folk-edges", False, "Nick Drake", None),
    ("Broadcast", "Haha Sound", 2003, 8.6, "art-pop", "art-pop", False, "Broadcast", None),
    ("Shellac", "At Action Park", 1994, 8.8, "rock", "noise-math", False, "Shellac",
     "Three men and the loudest, driest recording ever made, and not a wasted second."),
    ("Cocteau Twins", "Treasure", 1984, 9.0, "rock", "shoegaze-dream", False, "Cocteau Twins", None),
    ("Gillian Welch", "Time (The Revelator)", 2001, 9.1, "folk", "americana", False, "Gillian Welch",
     "Two people and two instruments telling American history sideways."),
    ("Songs: Ohia", "Didn't It Rain", 2002, 8.9, "rock", "americana", False, "Jason Molina", None),
    ("Brian Eno", "Ambient 1: Music for Airports", 1978, 9.4, "ambient", "ambient-retreat", False, "Brian Eno",
     "The record that invented the category, and still the most useful one in it."),
    ("Sonic Youth", "Daydream Nation", 1988, 9.4, "rock", "nineties-indie", False, "Sonic Youth", None),
    ("Curtis Mayfield", "There's No Place Like America Today", 1975, 9.0, "soul", "soul-corner", False, "Curtis Mayfield",
     "The bleakest and best of his records, and the arrangements are astonishing."),
    ("Bert Jansch", "Bert Jansch", 1965, 8.8, "folk", "folk-edges", False, "Bert Jansch", None),
    ("Dinosaur Jr.", "You're Living All Over Me", 1987, 9.0, "rock", "nineties-indie", False, "Dinosaur Jr.",
     "The loudest record about exhaustion, and a generation of guitarists stopped tuning up because of it."),
    ("Red House Painters", "Down Colorful Hill", 1992, 8.7, "rock", "slowcore", False, "Red House Painters", None),
    ("This Heat", "Deceit", 1981, 8.9, "rock", "post-punk", False, "Gang of Four", None),
    ("Young Marble Giants", "Colossal Youth", 1980, 9.0, "rock", "post-punk", False, "Dry Cleaning",
     "Post-punk reduced to bass, guitar, drum machine and a whisper, which turns out to be plenty."),
    ("Harold Budd", "The Pavilion of Dreams", 1978, 8.6, "ambient", "ambient-retreat", False, "Harold Budd", None),
    ("Julia Holter", "Have You in My Wilderness", 2015, 8.5, "art-pop", "art-pop", False, "Julia Holter", None),
    ("Built to Spill", "Perfect From Now On", 1997, 9.0, "rock", "nineties-indie", False, "Built to Spill",
     "Six long songs with real guitar solos, made when that was deeply unfashionable."),
    ("Lucinda Williams", "Car Wheels on a Gravel Road", 1998, 9.2, "americana", "americana", False, "Lucinda Williams", None),
    ("Don Caballero", "American Don", 2000, 8.4, "rock", "noise-math", False, "Don Caballero", None),
    ("Grouper", "Dragging a Dead Deer Up a Hill", 2008, 8.8, "ambient", "ambient-retreat", False, "Grouper",
     "Songs buried under so much tape hiss that finding them is the experience."),
    ("The Fall", "This Nation's Saving Grace", 1985, 9.1, "rock", "post-punk", False, "The Fall", None),
]

SINGLES = [
    # 001 Coil and Spring
    ("Sorry", "Right Round the Clock", "post-punk", "Dry Cleaning", None),
    ("Lice", "Arbiter", "post-punk", "Squid", None),
    ("Deeper", "Willing", "post-punk", "Protomartyr",
     "Chicago post-punk with the guitars wound tight enough to snap"),
    ("Preoccupations", "Espionage", "post-punk", "Wire", None),
    ("Public Body", "Naderia", "post-punk", "Gang of Four", None),
    # 002 Blue Weather
    ("Flyying Colours", "It's Tomorrow Now", "shoegaze-dream", "Ride", None),
    ("Whirr", "Home Is Where", "shoegaze-dream", "My Bloody Valentine", None),
    ("Nothing", "Vertigo Flowers", "shoegaze-dream", "Slowdive",
     "Philadelphia shoegaze that keeps the melody right at the front where it belongs"),
    ("Astrobrite", "Whitenoise Superstar", "shoegaze-dream", "My Bloody Valentine", None),
    ("Airiel", "Sugar Crystals", "shoegaze-dream", "Cocteau Twins", None),
    # 003 Whole Rooms Quiet
    ("Sun Kil Moon", "Carry Me Ohio", "slowcore", "Red House Painters", None),
    ("Bedhead", "Bedside Table", "slowcore", "Codeine",
     "Texas slowcore played so quietly you lean in, which is the entire trick"),
    ("Hood", "The Lost You", "slowcore", "Low", None),
    ("Julie Byrne", "Natural Blue", "slowcore", "Grouper", None),
    ("Ida", "Maybelle", "slowcore", "Duster", None),
    # 004 Loose Change
    ("Silver Jews", "Random Rules", "nineties-indie", "Pavement",
     "David Berman writing the funniest sad lines in the format, over the loosest band possible"),
    ("The Feelies", "Higher Ground", "nineties-indie", "Yo La Tengo", None),
    ("Chavez", "Break Up Your Band", "nineties-indie", "Built to Spill", None),
    ("Polvo", "Thermal Treasure", "nineties-indie", "Sonic Youth", None),
    ("Archers of Loaf", "Web in Front", "nineties-indie", "Modest Mouse", None),
    # 005 Kitchen Radio
    ("Cate Le Bon", "Daylight Matters", "art-pop", "Julia Holter",
     "Welsh art pop where every instrument sounds slightly wrong on purpose"),
    ("Aldous Harding", "The Barrel", "art-pop", "Weyes Blood", None),
    ("Molly Nilsson", "Hey Moon", "art-pop", "Broadcast", None),
    ("Anna Domino", "Rythm", "art-pop", "Kate Bush", None),
    ("Virginia Wing", "Rider", "art-pop", "Broadcast", None),
    # 006 Field Recording
    ("Shirley Collins", "Death and the Lady", "folk-edges", "Vashti Bunyan", None),
    ("Michael Chapman", "Postcards of Scarborough", "folk-edges", "Bert Jansch",
     "A Yorkshireman playing guitar like a session man and singing like a bricklayer"),
    ("Anne Briggs", "Blackwaterside", "folk-edges", "Vashti Bunyan", None),
    ("Nathan Salsburg", "Bluffs", "folk-edges", "Bert Jansch", None),
    ("Meg Baird", "Stars Climb Up the Vine", "folk-edges", "Linda Perhacs", None),
    # 007 Hard Angles
    ("June of 44", "Have a Safe Trip Dear", "noise-math", "Slint",
     "Nautical post-hardcore with the bass leading, and the tension never resolves"),
    ("Rodan", "Bible Silver Corner", "noise-math", "Slint", None),
    ("Storm & Stress", "Orbit Cadabra", "noise-math", "Don Caballero", None),
    ("Lightning Bolt", "Dracula Mountain", "noise-math", "Hella", None),
    ("Drive Like Jehu", "Here Come the Rome Plows", "noise-math", "Unwound", None),
    # 008 Long Drive
    ("Terry Allen", "Amarillo Highway", "americana", "Lucinda Williams",
     "A sculptor writing the best Texas songs of the seventies, entirely by accident"),
    ("Blaze Foley", "Clay Pigeons", "americana", "Jason Molina", None),
    ("Karen Dalton", "Something on Your Mind", "americana", "Gillian Welch",
     "A voice like a hard year, singing other people's songs better than they did"),
    ("Michael Hurley", "Werewolf", "americana", "Bonnie Prince Billy", None),
    ("Adrianne Lenker", "Anything", "americana", "Big Thief", None),
    # 009 Small Hours
    ("Gigi Masin", "Clouds", "ambient-retreat", "Harold Budd", None),
    ("Midori Takada", "Mr. Henri Rousseau's Dream", "ambient-retreat", "Hiroshi Yoshimura",
     "Percussion recorded in one take in a Japanese studio, and it sounds like a whole forest"),
    ("Laraaji", "Dance No. 1", "ambient-retreat", "Brian Eno", None),
    ("Ana Roxanne", "Camille", "ambient-retreat", "Grouper", None),
    ("Chihei Hatakeyama", "Towards a Tone", "ambient-retreat", "Harold Budd", None),
    # 010 Second Look
    ("Horsegirl", "Anti-Glory", "nineties-indie", "Sonic Youth",
     "Three teenagers who clearly own every record in this lane, and play like it"),
    ("MJ Lenderman", "Rudolph", "americana", "Big Thief", None),
    ("Water From Your Eyes", "Barley", "post-punk", "bar italia", None),
    ("Feeble Little Horse", "Freak", "shoegaze-dream", "Wednesday",
     "Noise pop assembled out of broken parts, and the melodies survive it"),
    ("Hotline TNT", "Protocol", "shoegaze-dream", "Ride", None),
    # 011 Late Summer
    ("Shuggie Otis", "Aht Uh Mi Hed", "soul-corner", "Bill Withers",
     "A teenager playing every instrument himself, and it swings harder than the session bands"),
    ("Syl Johnson", "Is It Because I'm Black", "soul-corner", "Curtis Mayfield", None),
    ("Bobbie Gentry", "Ode to Billie Joe", "soul-corner", "Ann Peebles",
     "Southern gothic delivered flat over one guitar, and nobody has bettered it"),
    ("Betty Davis", "If I'm in Luck I Might Get Picked Up", "soul-corner", "Bobby Womack", None),
    ("Terry Callier", "Dancing Girl", "folk-edges", "Bill Fay", None),
]

MIXES = [
    ("NTS Radio", "Nabihah Iqbal", "2026-05-30", "post-punk", 24, 7, "Wire", None),
    ("Dublab", "Carlos Niño", "2026-06-03", "ambient-retreat", 16, 4, "Brian Eno", None),
    ("NTS Radio", "Charlie Bones", "2026-06-06", "nineties-indie", 26, 9, "Pavement",
     "The breakfast show as a record collection, wandering wherever it likes for three hours"),
    ("Worldwide FM", "Lauren Laverne", "2026-06-10", "art-pop", 22, 8, "Kate Bush", None),
    ("NTS Radio", "Wednesday", "2026-06-13", "shoegaze-dream", 20, 5, "Wednesday",
     "A band playing the records they stole from, which is always the most honest kind of show"),
    ("The Lot Radio", "Adrianne Lenker", "2026-06-17", "americana", 18, 6, "Big Thief", None),
    ("NTS Radio", "Shirley Collins", "2026-06-20", "folk-edges", 15, 4, "Vashti Bunyan",
     "An eighty-year-old folk singer playing field recordings and explaining every one"),
    ("Dublab", "Julia Holter", "2026-06-24", "art-pop", 19, 5, "Julia Holter", None),
    ("NTS Radio", "Slowdive", "2026-06-27", "shoegaze-dream", 23, 7, "Slowdive", None),
    ("Worldwide FM", "Gilles Peterson", "2026-07-01", "soul-corner", 25, 8, "Bill Withers", None),
    ("NTS Radio", "Iceage", "2026-07-04", "post-punk", 28, 6, "Protomartyr", None),
    ("The Lot Radio", "Grouper", "2026-07-08", "ambient-retreat", 14, 3, "Grouper",
     "Two hours of near-silence programmed by someone who understands why that is generous"),
    ("NTS Radio", "Steve Albini", "2026-07-11", "noise-math", 21, 6, "Shellac", None),
    ("Dublab", "Meg Baird", "2026-07-15", "folk-edges", 17, 5, "Bert Jansch", None),
    ("NTS Radio", "Yo La Tengo", "2026-07-18", "nineties-indie", 24, 10, "Yo La Tengo",
     "Three people who have heard everything, playing the parts of it nobody else remembers"),
    ("Worldwide FM", "Emma Warren", "2026-07-22", "post-punk", 20, 6, "Gang of Four", None),
    ("NTS Radio", "MJ Lenderman", "2026-07-25", "americana", 22, 7, "Jason Molina", None),
    ("Dublab", "Laraaji", "2026-07-29", "ambient-retreat", 13, 3, "Harold Budd", None),
    ("NTS Radio", "Cate Le Bon", "2026-08-01", "art-pop", 18, 5, "Broadcast", None),
    ("The Lot Radio", "Horsegirl", "2026-08-05", "nineties-indie", 21, 8, "Sonic Youth",
     "Teenagers playing nineties records with more reverence than the people who made them"),
    ("NTS Radio", "Dry Cleaning", "2026-08-08", "post-punk", 26, 8, "Dry Cleaning", None),
    ("Worldwide FM", "Bradley Zero", "2026-08-15", "soul-corner", 23, 7, "Curtis Mayfield", None),
]

REVIVALS = [
    ("Slowdive", "Alison", "Souvlaki", 58, "2024-06-18", "shoegaze-dream",
     "Played more than anything else you own one autumn, then set down completely"),
    ("Pavement", "Gold Soundz", "Crooked Rain", 52, "2024-04-22", "nineties-indie",
     "The most-played song in your record for two straight years, and silent since"),
    ("Duster", "Inside Out", "Stratosphere", 46, "2023-11-14", "slowcore",
     "The quietest thing you have ever played this many times"),
    ("Television", "Venus", "Marquee Moon", 41, "2024-02-08", "post-punk",
     "One of the great guitar conversations, and it has been off the shelf for a while"),
    ("Low", "Sunflower", "Things We Lost in the Fire", 38, "2024-05-30", "slowcore",
     "Two voices and almost nothing else, and it used to be a weekly habit"),
    ("My Bloody Valentine", "Only Shallow", "Loveless", 49, "2024-07-11", "shoegaze-dream",
     "Played until the opening drums stopped landing, which takes some doing"),
    ("Yo La Tengo", "Autumn Sweater", None, 44, "2024-03-19", "nineties-indie",
     "A song about being uncomfortable at a party, played through an entire uncomfortable year"),
    ("Talk Talk", "New Grass", "Laughing Stock", 27, "2024-08-02", "art-pop", None),
    ("Kate Bush", "Running Up That Hill", "Hounds of Love", 36, "2024-01-25", "art-pop", None),
    ("Nick Drake", "Place to Be", "Pink Moon", 33, "2023-12-09", "folk-edges", None),
    ("Vashti Bunyan", "Diamond Day", None, 24, "2024-04-06", "folk-edges", None),
    ("Slint", "Good Morning, Captain", "Spiderland", 42, "2024-06-27", "noise-math",
     "The loudest thing in a quiet record collection, and it has been silent since July"),
    ("Shellac", "Prayer to God", "1000 Hurts", 31, "2024-02-29", "noise-math", None),
    ("Unwound", "Corpse Pose", None, 26, "2023-10-21", "noise-math", None),
    ("Big Thief", "Not", "Two Hands", 47, "2024-05-14", "americana",
     "A guitar solo you used to wait all song for, untouched for over a year"),
    ("Jason Molina", "Farewell Transmission", "Magnolia Electric Co", 39, "2024-07-23", "americana",
     "Eight minutes that used to get played weekly, and have not been touched in over a year"),
    ("Lucinda Williams", "Right in Time", None, 22, "2024-03-11", "americana", None),
    ("Brian Eno", "1/1", "Music for Airports", 29, "2024-08-08", "ambient-retreat", None),
    ("Grouper", "Heavy Water", None, 34, "2024-06-04", "ambient-retreat", None),
    ("Hiroshi Yoshimura", "Creek", "Green", 21, "2024-01-16", "ambient-retreat", None),
    ("Bill Withers", "Hope She'll Be Happier", None, 28, "2024-05-21", "soul-corner",
     "A live recording of a man alone on stage, and it gets harder to play the older you get"),
    ("Curtis Mayfield", "The Makings of You", None, 25, "2024-02-18", "soul-corner", None),
    ("Ann Peebles", "Breaking Up Somebody's Home", None, 23, "2023-11-28", "soul-corner", None),
    ("Wire", "Outdoor Miner", "Chairs Missing", 32, "2024-04-30", "post-punk", None),
    ("The Fall", "Bill Is Dead", None, 30, "2024-07-16", "post-punk", None),
    ("Dry Cleaning", "Scratchcard Lanyard", "New Long Leg", 37, "2024-06-11", "post-punk",
     "Played constantly the month it came out and then filed away entirely"),
    ("Cocteau Twins", "Cherry-Coloured Funk", "Heaven or Las Vegas", 35, "2024-03-26", "shoegaze-dream", None),
    ("Beach House", "Myth", "Bloom", 43, "2024-08-13", "shoegaze-dream",
     "Worn down by repetition rather than boredom, which is a different kind of ending"),
    ("Ride", "Vapour Trail", None, 26, "2024-01-09", "shoegaze-dream", None),
    ("Built to Spill", "Carry the Zero", None, 29, "2024-05-07", "nineties-indie", None),
    ("Dinosaur Jr.", "Feel the Pain", None, 27, "2023-12-19", "nineties-indie", None),
    ("Red House Painters", "Katy Song", None, 31, "2024-04-16", "slowcore", None),
    ("Codeine", "Tom", None, 20, "2024-02-06", "slowcore", None),
]

RELEASES = [
    ("Dry Cleaning", "Stumpwork Sessions", "ep", "The band's oddest material, which is usually the best."),
    ("Wednesday", "Bleeds", "album", None),
    ("Big Thief", "Double Infinity", "album", "A Big Thief record is still an event in this house."),
    ("bar italia", "Tracey Denim Deluxe", "album", None),
    ("Slowdive", "Everything Is Alive Remixes", "compilation", None),
    ("Beach House", "Once Twice Melody Live", "compilation", "Recorded on the tour, and the reverb sounds enormous in a room."),
    ("Protomartyr", "Formal Growth in the Desert", "album", None),
    ("Squid", "Cowards", "album", None),
    ("Yo La Tengo", "This Stupid World Live", "compilation", "Still touring, still improvising, still worth it."),
    ("Pavement", "Wowee Zowee Reissue", "compilation", None),
    ("Sonic Youth", "Walls Have Ears Reissue", "compilation", "The bootleg they hated, finally released properly."),
    ("Built to Spill", "When the Wind Forgets Your Name", "album", None),
    ("Modest Mouse", "The Golden Casket B-Sides", "ep", None),
    ("Guided by Voices", "Strut of Kings", "album", "He puts out three records a year and one of them is always great."),
    ("Kate Bush", "The Other Sides", "compilation", None),
    ("Weyes Blood", "In Holy Flux", "album", "The third part of the trilogy, and the arrangements keep growing."),
    ("Julia Holter", "Something in the Room She Moves", "album", None),
    ("Broadcast", "Distant Call Reissue", "compilation", None),
    ("Talk Talk", "Spirit of Eden Remaster", "compilation", "Remastered from the original tapes, which matters on a record this quiet."),
    ("Low", "Hey What Sessions", "ep", None),
    ("Duster", "In Dreams", "album", "They reunited and the records are somehow just as bleak."),
    ("Red House Painters", "Ocean Beach Reissue", "compilation", None),
    ("Codeine", "Dessau Reissue", "compilation", None),
    ("Grouper", "Ruins Reissue", "compilation", None),
    ("Vashti Bunyan", "Lookaftering Reissue", "compilation", None),
    ("Bert Jansch", "Live at the 12 Bar", "compilation", "Recorded late in his life, and the playing is unbelievable."),
    ("Bill Fay", "Tomorrow Tomorrow and Tomorrow", "album", None),
    ("Nick Drake", "The Making of Five Leaves Left", "compilation", None),
    ("Linda Perhacs", "Parallelograms Reissue", "compilation", None),
    ("Slint", "Spiderland Deluxe", "compilation", "Two discs of demos from the record that broke everything open."),
    ("Shellac", "To All Trains", "album", None),
    ("Unwound", "Empire Reissue", "compilation", None),
    ("Don Caballero", "American Don Reissue", "compilation", None),
    ("Hella", "Hold Your Horse Is Reissue", "compilation", None),
    ("Lucinda Williams", "Stories From a Rock N Roll Heart", "album", "She keeps writing after everything, which is the whole point of her."),
    ("Jason Molina", "Live at Third Man", "compilation", None),
    ("Bonnie Prince Billy", "Keeping Secrets Will Destroy You", "album", None),
    ("Gillian Welch", "Woodland", "album", "The first new songs in years, recorded in their own repaired studio."),
    ("Brian Eno", "Forever and Ever No More", "album", None),
    ("Hiroshi Yoshimura", "Flora Reissue", "compilation", "The reissue campaign keeps finding more, and it is all this good."),
    ("Harold Budd", "The Room Reissue", "compilation", None),
    ("Bill Withers", "Live at Carnegie Hall Deluxe", "compilation", None),
    ("Curtis Mayfield", "Roots Remaster", "compilation", None),
    ("Ann Peebles", "Straight From the Heart Reissue", "compilation", None),
    ("Bobby Womack", "Understanding Reissue", "compilation", None),
    ("Television", "Live at the Old Waldorf", "compilation", "A soundboard tape from seventy-eight, and the guitars are pristine."),
    ("Wire", "Not About to Die", "compilation", None),
    ("The Fall", "Live at St Helens", "compilation", None),
    ("Gang of Four", "Entertainment Reissue", "compilation", None),
    ("My Bloody Valentine", "Loveless Remaster", "compilation", "Remastered again, and people will argue about it again."),
    ("Cocteau Twins", "Treasure Reissue", "compilation", None),
    ("Ride", "Interplay", "album", None),
    ("Dinosaur Jr.", "Sweep It Into Space Live", "compilation", None),
    ("Big Thief", "Vampire Empire", "single", None),
    ("Big Thief", "Bright Future Sessions", "ep", "Recorded to tape in a cabin, and you can hear the chair creak."),
]

CATALOGS_POOL = [
    ("Pavement", 44, 38, ["Gold Soundz", "Range Life", "Cut Your Hair", "Summer Babe"],
     [("Brighten the Corners", 1997), ("Terror Twilight", 1999)],
     "Two albums played to death and the two strangest ones never opened."),
    ("Yo La Tengo", 38, 34, ["Autumn Sweater", "Our Way to Fall", "Tom Courtenay"],
     [("I Can Hear the Heart Beating as One", 1997), ("Fakebook", 1990)],
     "A catalogue of fifteen records reduced to the two everyone recommends."),
    ("Talk Talk", 14, 58, ["New Grass", "It's My Life", "Life's What You Make It"],
     [("The Party's Over", 1982), ("The Colour of Spring", 1986)],
     "The pop singles get played and the two records they are famous for do not."),
    ("Kate Bush", 26, 47, ["Running Up That Hill", "Cloudbusting", "Hounds of Love"],
     [("The Dreaming", 1982), ("Aerial", 2005)],
     "One album in heavy rotation and the weirder, better ones untouched."),
    ("My Bloody Valentine", 18, 52, ["Only Shallow", "Soon", "When You Sleep"],
     [("Isn't Anything", 1988), ("EPs 1988-1991", 2012)],
     "Loveless is the whole relationship, and the record before it is nearly as good."),
    ("Sonic Youth", 41, 31, ["Teen Age Riot", "Schizophrenia", "Kool Thing"],
     [("Sister", 1987), ("Washing Machine", 1995)],
     "A thirty-year catalogue and you have played four years of it."),
    ("Low", 29, 42, ["Sunflower", "Dinosaur Act", "Words"],
     [("Double Negative", 2018), ("Hey What", 2021)],
     "The quiet albums get played constantly and the loud late ones never do."),
]

if __name__ == "__main__":
    write(META, LANES, ARTISTS, ISSUES, ALBUMS, CRITICS, SINGLES, MIXES,
          REVIVALS, RELEASES, CATALOGS_POOL)
