"""Fill the 'andrew' catalog's remaining pools: singles, mixes, revivals,
releases, catalog rooms.

Writing is concentrated where it shows: every catalog room speaks, and the
notes on singles, mixes and revivals cluster in the later issues (the ones a
demo actually opens). Bare rows get the generator's receipt prose, which is
how the engine writes without an LLM.

Run:  python3 demo/author_andrew_pools.py   (after author_andrew.py)
"""

import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "catalogs" / "andrew.json"

# ------------------------------------------------------------- singles (90)
# artist, title, lane, anchor, note|None  — five per issue, eighteen issues
SINGLES = [
    # 001 Long Grass
    ("Sam Gendel", "Saint Cloud", "jazz-bridge", "Nujabes", None),
    ("Green-House", "Peperomia", "the-mist", "Tycho", None),
    ("Sault", "Wildfires", "cosmic-groove", "The Blaze", None),
    ("Kelly Lee Owens", "Melt!", "club-continuum", "Four Tet", None),
    ("Fatima", "Family", "jazz-bridge", "KAYTRANADA", None),
    # 002 Sunlit Rust
    ("Durand Jones & The Indications", "Long Way Home", "cosmic-groove", "Khruangbin", None),
    ("Mildlife", "Downstream", "cosmic-groove", "The Donkeys", None),
    ("Kiefer", "Bridges", "beats-idm", "Blockhead", None),
    ("Tatsuro Yamashita", "Sparkle", "cosmic-groove", "Jai Paul", None),
    ("Say She She", "Forget Me Not", "cosmic-groove", "The Pharcyde", None),
    # 003 Weight of Water
    ("Ulla", "Something Made of Nothing", "the-mist", "Ana Roxanne", None),
    ("Huerco S.", "A Sea of Love", "the-mist", "The Field", None),
    ("claire rousay", "peak chroma", "the-mist", "Ana Roxanne", None),
    ("Ana Roxanne", "Venus", "the-mist", "Ana Roxanne", None),
    ("Pauline Anna Strom", "Marking Time", "the-mist", "Tycho", None),
    # 004 Small Hours Garage
    ("Sammy Virji", "Shella's Riddim", "house-garage", "Disclosure",
     "UK garage built for a soundsystem rather than a laptop, and it swings hard enough to prove it"),
    ("Interplanetary Criminal", "Tell Me", "house-garage", "Fred again..",
     "Bassline house with a vocal chopped into pure rhythm, made by someone who clearly loves the nineties"),
    ("Salute", "Deep Cuts", "house-garage", "ANOTR", None),
    ("Barry Can't Swim", "Sunsleeper", "house-garage", "Folamour", None),
    ("India Jordan", "For You", "house-garage", "Joe Goddard", None),
    # 005 Paper Trail
    ("Rome Streetz", "Long Story Short", "underground-rap", "Westside Gunn",
     "Harlem rapping at the pace of a man telling you something in confidence, over one loop that never changes"),
    ("Boldy James", "Brickmile to Montana", "underground-rap", "The Alchemist",
     "The flattest, calmest delivery in rap over beats that keep getting further out"),
    ("Nicholas Craven", "Craven N", "underground-rap", "Larry June", None),
    ("al.divino", "Vermont", "underground-rap", "Estee Nack", None),
    ("Stove God Cooks", "Panda Bear", "underground-rap", "Pusha T", None),
    # 006 Green Room
    ("Kokoroko", "Abusey Junction", "jazz-bridge", "Yussef Dayes",
     "West African highlife guitar recorded in London, and it takes its time getting anywhere"),
    ("Emma-Jean Thackray", "Say Something", "jazz-bridge", "Robert Glasper",
     "A trumpeter who arranges like a producer, which is why this sounds like a band and a machine at once"),
    ("Joe Armon-Jones", "Icy Roads", "jazz-bridge", "Butcher Brown", None),
    ("Alfa Mist", "Keep On", "jazz-bridge", "Nujabes", None),
    ("Nubya Garcia", "Source", "jazz-bridge", "Hiatus Kaiyote", None),
    # 007 Static Bloom
    ("Seefeel", "Time to Find Me", "the-mist", "Maribou State",
     "Shoegaze fed through early Warp electronics, and the guitars stop behaving like guitars entirely"),
    ("Windy & Carl", "Fainting in Coils", "the-mist", "Bonobo", None),
    ("Bark Psychosis", "Big Shot", "punk-turn", "bar italia", None),
    ("Slowdive", "Souvlaki Space Station", "the-mist", "Tycho",
     "The band at their most weightless, which is the mode everything since has tried to copy"),
    ("Labradford", "Twenty", "the-mist", "The Field", None),
    # 008 Held Note
    ("Yaeji", "Raingurl", "house-garage", "Fred again..",
     "Half-whispered in two languages over a house beat, and somehow enormous"),
    ("Men I Trust", "Show Me How", "cosmic-groove", "The Blaze", None),
    ("Nilüfer Yanya", "Stabilise", "punk-turn", "Dry Cleaning", None),
    ("Tirzah", "Devotion", "beats-idm", "Sampha", None),
    ("Erika de Casier", "Do My Thing", "cosmic-groove", "Jai Paul", None),
    # 009 Low Sun
    ("Michael McDonald", "I Keep Forgettin'", "dad-rock", "Steely Dan",
     "The most expensive-sounding four minutes of the early eighties, played by the same session men you already love"),
    ("Ned Doheny", "Get It Up for Love", "dad-rock", "Fleetwood Mac",
     "Laurel Canyon soft rock with a real groove under it, ignored at the time and perfect now"),
    ("Pages", "Clearly Kim", "dad-rock", "Steely Dan", None),
    ("Bill LaBounty", "Livin' It Up", "dad-rock", "Dire Straits", None),
    ("Gene Clark", "Some Misunderstanding", "dad-rock", "Bob Dylan", None),
    # 010 Reservoir
    ("Donato Dozzy", "Vaporware 04", "club-continuum", "Floating Points",
     "One idea turned very slowly for eight minutes, which is the whole appeal"),
    ("Wolfgang Voigt", "Königsforst", "the-mist", "The Field", None),
    ("Vladislav Delay", "Raamat", "the-mist", "Ana Roxanne", None),
    ("Skee Mask", "Rev8617", "beats-idm", "Boards of Canada",
     "Breakbeats and grey ambience in the same track, from the most reliable producer in Munich"),
    ("Lawrence", "Along the Wall", "club-continuum", "DJ Koze", None),
    # 011 Copper Wire
    ("Alan Braxe", "Vertigo", "french-electronic", "Étienne de Crécy",
     "French touch at its most elegant, one filtered loop and absolute confidence"),
    ("Fred Falke", "Untitled Love", "french-electronic", "Breakbot", None),
    ("Bob Sinclar", "My Only Love", "french-electronic", "Cassius", None),
    ("Le Knight Club", "Hysteria", "french-electronic", "Justice", None),
    ("Demon", "You Are My High", "french-electronic", "Étienne de Crécy", None),
    # 012 Night Kitchen
    ("Sniffany & The Nits", "The Gnats", "punk-turn", "Viagra Boys",
     "Genuinely unhinged London punk that is also very funny, which is a rare combination"),
    ("Been Stellar", "Sweet", "punk-turn", "Fontaines D.C.", None),
    ("Militarie Gun", "Do It Faster", "punk-turn", "Turnstile",
     "Hardcore that decided to write choruses, and the choruses are good"),
    ("Sprints", "Literary Mind", "punk-turn", "Dry Cleaning", None),
    ("Gilla Band", "Eight Bells", "punk-turn", "bar italia", None),
    # 013 Salt Print
    ("Smith & Mighty", "Walk On", "beats-idm", "Nightmares On Wax",
     "The Bristol sound before anyone named it, dub weight under a pop song"),
    ("Andy Stott", "Numb", "beats-idm", "Burial", None),
    ("Moritz von Oswald Trio", "Structure 1", "beats-idm", "The Field", None),
    ("Theo Parrish", "Falling Up", "house-garage", "Folamour",
     "Detroit house mixed like a jazz record, deliberately rough, and it never stops moving"),
    ("Omar S", "Psychotic Photosynthesis", "house-garage", "ANOTR", None),
    # 014 Cold Front
    ("Lenzman", "Open Page", "liquid", "Calibre",
     "Dutch liquid with a hip hop producer's ear for space between the drums"),
    ("dBridge", "Inner Disbelief", "liquid", "Netsky",
     "The colder, more introverted end of drum and bass, made by one of its architects"),
    ("Hydro", "The Chase", "liquid", "High Contrast", None),
    ("Break", "Hurt You", "liquid", "Sub Focus", None),
    ("LSB", "Missing You", "liquid", "Hybrid Minds",
     "Rolling, unhurried drum and bass with a soul vocal buried in the middle distance, which is the version of this you actually finish."),
    # 015 Open Tuning
    ("Bill Callahan", "Jim Cain", "dad-rock", "Bob Dylan",
     "A deep, dry voice singing plain sentences over almost nothing, and somehow the warmest thing here."),
    ("Ryley Walker", "Primrose Green", "dad-rock", "Grateful Dead",
     "Chicago guitar playing that runs straight through British folk and comes out jazz."),
    ("Hiss Golden Messenger", "Red Rose Nantahala", "dad-rock", "Creedence Clearwater Revival", None),
    ("Nathan Salsburg", "Bluffs", "dad-rock", "Bob Dylan", None),
    ("Sarah Louise", "Gestures in Kind", "the-mist", "Ana Roxanne",
     "Twelve-string guitar recorded like ambient music, which is the trick nobody else pulls off."),
    # 016 Second Wind
    ("Jessica Pratt", "Back, Baby", "cosmic-groove", "The Donkeys",
     "Sung close to the microphone in a voice from another decade, and it holds a room instantly."),
    ("Duval Timothy", "Through the Night", "jazz-bridge", "Sampha",
     "Piano recorded with the room left in, made by the man who plays on the Sampha records you know."),
    ("Iglooghost", "Sylph Fables", "beats-idm", "Flying Lotus",
     "Drums that keep falling over and getting back up, arranged with real tenderness underneath."),
    ("Fred again..", "Marea (We've Lost Dancing)", "house-garage", "Fred again..", None),
    ("Overmono", "So U Kno", "house-garage", "Disclosure",
     "Welsh brothers turning a hardcore rave sample into something patient and huge."),
    # 017 Glass Field
    ("Biosphere", "Kobresia", "the-mist", "The Field",
     "An orchestra buried under a kick drum in a German forest, and the most total immersion on this list."),
    ("The Field", "Over the Ice", "beats-idm", "The Field", None),
    ("Marcel Dettmann", "Seduction", "club-continuum", "Jeff Mills" if False else "DJ Koze",
     "Berlin techno with the mid-range scooped out, which leaves an enormous amount of space to sit in."),
    ("Barker", "Hedonic Treadmill", "club-continuum", "Floating Points",
     "Techno with no kick drum at all, and it still moves, which is the whole argument."),
    ("Lorenzo Senni", "Discipline of Enthusiasm", "bass-edm", "Space Laces",
     "Trance reduced to only its build-ups, held there forever, and stranger than it sounds."),
    # 018 Last Light
    ("Nala Sinephro", "Continuum 1", "jazz-bridge", "Robert Glasper",
     "Harp and modular synth breathing in the same tempo, recorded in one room with nothing rushed."),
    ("Vegyn", "Blue Verb", "beats-idm", "Flying Lotus", None),
    ("Yu Su", "Xiu", "club-continuum", "Jacques Greene",
     "Dance music built from field recordings and patience, made in Vancouver and sounding like nowhere."),
    ("Photay", "Aery Metaphor", "beats-idm", "Emancipator", None),
    ("Blue Lake", "Sun Arcs", "the-mist", "Tycho",
     "A zither built by hand in Copenhagen, played until it sounds like a small orchestra."),
]

# --------------------------------------------------------------- mixes (36)
# show, host, date, lane, tracks_total, known, anchor, note|None
MIXES = [
    ("Beats in Space", "Tim Sweeney", "2026-03-14", "club-continuum", 22, 6, "DJ Koze", None),
    ("Sounds of the Dawn", "Nate Scheible", "2026-03-21", "the-mist", 14, 4, "Tycho", None),
    ("Rinse FM", "Sherelle", "2026-03-28", "bass-edm", 31, 8, "Skrillex", None),
    ("Do!! You!!! Breakfast Show", "Charlie Bones", "2026-04-04", "cosmic-groove", 26, 7, "Khruangbin", None),
    ("Worldwide FM", "Gilles Peterson", "2026-04-11", "jazz-bridge", 24, 9, "Nujabes",
     "The man who has been building the bridge between jazz and everything else for forty years"),
    ("NTS Breakfast Show", "Flo Dill", "2026-04-18", "house-garage", 28, 8, "Disclosure", None),
    ("Balamii", "Sam Binga", "2026-04-25", "liquid", 33, 10, "High Contrast",
     "Bristol bass across every tempo it comes in, mixed like someone who plays out every week"),
    ("The Lot Radio", "Anthony Naples", "2026-05-02", "club-continuum", 19, 5, "Four Tet", None),
    ("Dublab", "Carlos Niño", "2026-05-09", "jazz-bridge", 17, 5, "Robert Glasper", None),
    ("NTS Radio", "Ben UFO", "2026-05-16", "house-garage", 35, 11, "Fred again..",
     "The most trusted selector in UK dance music, moving between decades without a seam"),
    ("Rinse FM", "Alix Perez", "2026-05-23", "liquid", 29, 9, "Calibre",
     "Two hours of the deeper, moodier side of drum and bass from someone who helped define it"),
    ("Mixmag Lab", "Folamour", "2026-05-30", "house-garage", 21, 6, "Folamour", None),
    ("NTS Radio", "Shy One", "2026-06-06", "beats-idm", 27, 7, "Flying Lotus", None),
    ("Worldwide FM", "Bradley Zero", "2026-06-13", "cosmic-groove", 23, 8, "The Pharcyde", None),
    ("Sounds of the Dawn", "Nate Scheible", "2026-06-20", "the-mist", 16, 4, "Ana Roxanne",
     "New age obscurities pulled from tape, sequenced for actual listening rather than novelty"),
    ("NTS Radio", "Loraine James", "2026-06-27", "beats-idm", 25, 6, "Boards of Canada",
     "A producer playing the records that made her, which is always the most revealing kind of show"),
    ("Rinse FM", "Interplanetary Criminal", "2026-07-04", "house-garage", 30, 9, "ANOTR", None),
    ("Beats in Space", "Todd Terje", "2026-07-11", "club-continuum", 20, 7, "Todd Terje", None),
    ("NTS Radio", "Ossia", "2026-07-18", "bass-edm", 26, 6, "Burial",
     "Bristol dub weight played at half speed, with more space in it than anything else on the dial."),
    ("Dublab", "Jerry Paper", "2026-07-25", "cosmic-groove", 18, 5, "The Donkeys", None),
    ("NTS Radio", "Anz", "2026-08-01", "house-garage", 32, 10, "Joe Goddard",
     "Manchester club radio that keeps changing its mind, which is why the hour never sags."),
    ("Worldwide FM", "Nabihah Iqbal", "2026-08-08", "punk-turn", 22, 6, "Dry Cleaning", None),
    ("NTS Radio", "Yussef Dayes", "2026-08-15", "jazz-bridge", 19, 7, "Yussef Dayes",
     "A drummer programming a radio show, which means the sequencing is about feel and nothing else."),
    ("Rinse FM", "Nia Archives", "2026-03-07", "liquid", 28, 8, "Netsky", None),
    ("NTS Radio", "Object Blue", "2026-02-28", "club-continuum", 24, 5, "Jacques Greene", None),
    ("Balamii", "Kessler", "2026-02-21", "house-garage", 27, 7, "Fred again..", None),
    ("The Lot Radio", "DJ Python", "2026-02-14", "the-mist", 21, 6, "Maribou State", None),
    ("Do!! You!!! Breakfast Show", "Charlie Bones", "2026-02-07", "dad-rock", 25, 9, "Grateful Dead", None),
    ("NTS Radio", "Moxie", "2026-01-31", "house-garage", 29, 8, "Disclosure", None),
    ("Worldwide FM", "Emma-Jean Thackray", "2026-01-24", "jazz-bridge", 20, 6, "Butcher Brown", None),
    ("Rinse FM", "Sicaria", "2026-01-17", "bass-edm", 31, 7, "Space Laces", None),
    ("NTS Radio", "Tim Reaper", "2026-01-10", "liquid", 34, 9, "London Elektricity",
     "Jungle played by someone who never stopped making it, and the tempo never once relents."),
    ("Dublab", "Green-House", "2026-01-03", "the-mist", 15, 4, "Tycho", None),
    ("NTS Radio", "Skee Mask", "2025-12-27", "beats-idm", 26, 6, "Boards of Canada", None),
    ("Beats in Space", "Eris Drew", "2025-12-20", "club-continuum", 23, 5, "DJ Koze", None),
    ("NTS Radio", "Sofia Kourtesis", "2025-12-13", "house-garage", 22, 7, "Folamour", None),
]

# ------------------------------------------------------------ revivals (54)
# artist, title, album, plays, last_played, lane, note|None
REVIVALS = [
    ("Sewerslvt", "Mr. Kill Myself", None, 52, "2024-06-27", "bass-edm", None),
    ("Groundislava", "Girl Behind the Glass", "Feel Me", 47, "2023-11-02", "beats-idm", None),
    ("Emancipator", "Anthem", "Safe in the Steep Cliffs", 41, "2024-02-18", "beats-idm", None),
    ("Skrillex", "Ragga Bomb", "Recess", 63, "2023-08-14", "bass-edm",
     "The loudest thing in your listening for one long stretch, then complete silence"),
    ("KOAN Sound", "Sly Fox", "Dynasty", 38, "2024-01-09", "bass-edm", None),
    ("Nujabes", "Aruarian Dance", "Departure", 55, "2024-09-30", "jazz-bridge",
     "The most-played song in a whole era of your listening, and untouched since"),
    ("Tycho", "A Walk", "Dive", 44, "2023-12-11", "the-mist", None),
    ("Bonobo", "Kiara", "Black Sands", 39, "2024-03-22", "the-mist", None),
    ("Four Tet", "Angel Echoes", "There Is Love in You", 36, "2023-10-05", "club-continuum", None),
    ("Khruangbin", "White Gloves", "The Universe Smiles Upon You", 58, "2024-05-19", "cosmic-groove",
     "Played more than almost anything else you own, and then set down mid-sentence"),
    ("The Blaze", "Territory", "Dancehall", 42, "2023-09-27", "cosmic-groove", None),
    ("Jai Paul", "BTSTU", None, 34, "2024-04-13", "cosmic-groove", None),
    ("MF DOOM", "Rapp Snitch Knishes", "Mm..Food", 49, "2024-07-08", "underground-rap", None),
    ("Westside Gunn", "Dr. Birds", "Pray for Paris", 31, "2024-02-29", "underground-rap", None),
    ("Denzel Curry", "Ricky", "ZUU", 46, "2023-11-16", "underground-rap", None),
    ("High Contrast", "Racing Green", "Tough Guys Don't Dance", 37, "2024-01-27", "liquid", None),
    ("Netsky", "Iron Heart", "Netsky", 33, "2023-12-30", "liquid", None),
    ("Sub Focus", "Rock It", "Sub Focus", 40, "2024-06-04", "liquid", None),
    ("Steely Dan", "Aja", "Aja", 29, "2024-08-21", "dad-rock", None),
    ("Dire Straits", "Telegraph Road", "Love Over Gold", 26, "2024-05-08", "dad-rock", None),
    ("Grateful Dead", "Eyes of the World", "Wake of the Flood", 24, "2023-10-19", "dad-rock", None),
    ("Viagra Boys", "Sports", "Street Worms", 43, "2024-03-15", "punk-turn", None),
    ("Turnstile", "Blackout", "Glow On", 51, "2024-04-27", "punk-turn",
     "A song that soundtracked one specific summer and then got put away with it"),
    ("Fontaines D.C.", "Boys in the Better Land", "Dogrel", 28, "2023-09-11", "punk-turn", None),
    ("Disclosure", "Latch", "Settle", 45, "2024-07-23", "house-garage",
     "Everyone wore this one out, you included, and enough time has passed to hear it again"),
    ("Folamour", "The Journey", "Ordinary Drugs", 22, "2024-02-06", "house-garage", None),
    ("Flying Lotus", "Never Catch Me", "You're Dead!", 48, "2024-06-15", "beats-idm",
     "Kendrick over a drum pattern nobody else would have dared, and it still sounds like an emergency"),
    ("Nightmares On Wax", "Les Nuits", "Smokers Delight", 35, "2023-11-28", "the-mist", None),
    ("Blockhead", "The Music Scene", "The Music Scene", 30, "2024-01-14", "beats-idm", None),
    ("Bibio", "Lovers' Carvings", "Ambivalence Avenue", 27, "2023-12-05", "beats-idm", None),
    ("DJ Koze", "Pick Up", "Knock Knock", 32, "2024-05-26", "club-continuum", None),
    ("Jacques Greene", "Another Girl", "Concealer", 25, "2024-03-08", "club-continuum", None),
    ("Étienne de Crécy", "Am I Wrong", "Super Discount", 38, "2024-08-04", "french-electronic",
     "One filtered loop, six minutes, and it has not aged a day since you last played it"),
    ("Justice", "Genesis", "Cross", 44, "2023-10-27", "french-electronic", None),
    ("Cassius", "Feeling for You", "1999", 21, "2024-04-06", "french-electronic", None),
    ("KAYTRANADA", "Glowed Up", "99.9%", 41, "2024-07-14", "jazz-bridge", None),
    ("Robert Glasper", "Afro Blue", "Black Radio", 23, "2024-02-11", "jazz-bridge", None),
    ("Sampha", "Blood on Me", "Process", 37, "2024-06-22", "the-mist",
     "A panic attack arranged for piano and drums, and one of the best vocals of the decade"),
    ("Maribou State", "Midas", "Portraits", 34, "2023-11-09", "the-mist",
     "Played into the ground one autumn and then dropped entirely, which is the shape of a song you used up."),
    ("Yves Tumor", "Gospel for a New Century", "Heaven to a Tortured Mind", 29, "2024-05-31", "cosmic-groove", None),
    ("The Pharcyde", "Runnin'", "Labcabincalifornia", 39, "2024-01-20", "cosmic-groove", None),
    ("Pusha T", "Numbers on the Boards", "My Name Is My Name", 26, "2023-12-17", "underground-rap", None),
    ("Larry June", "Smoothies in 1993", "Spaceships on the Blade", 31, "2024-08-11", "underground-rap", None),
    ("Estee Nack", "Nackmatical", None, 20, "2024-03-29", "underground-rap", None),
    ("Calibre", "Mystic", "Second Sun", 24, "2024-04-20", "liquid", None),
    ("Hybrid Minds", "Halcyon", "Mountains", 28, "2023-10-12", "liquid",
     "A whole winter of late drives lives in this one, and it has not been played since that winter ended."),
    ("Fleetwood Mac", "Gold Dust Woman", "Rumours", 22, "2024-07-06", "dad-rock", None),
    ("Bob Dylan", "Shelter from the Storm", "Blood on the Tracks", 25, "2024-02-24", "dad-rock", None),
    ("Dry Cleaning", "Scratchcard Lanyard", "New Long Leg", 33, "2024-06-08", "punk-turn", None),
    ("bar italia", "Nurse!", "Tracey Denim", 19, "2024-05-11", "punk-turn", None),
    ("Fred again..", "Delilah (pull me out of this)", "Actual Life 3", 47, "2024-08-18", "house-garage",
     "Played constantly for one month and then never again, which is what happens to a song that is about a moment."),
    ("Joe Goddard", "Gabriel", None, 23, "2023-09-22", "house-garage", None),
    ("Above & Beyond", "Sun & Moon", "Group Therapy", 30, "2024-01-06", "the-mist", None),
    ("Thievery Corporation", "Lebanese Blonde", "The Mirror Conspiracy", 27, "2023-12-24", "cosmic-groove", None),
]

# ------------------------------------------------------------ releases (90)
# artist, title, release_type, note|None
RELEASES = [
    ("Bonobo", "Nowhere Diaries", "album", "A new Bonobo record, which historically means a fortnight of nothing else."),
    ("Flying Lotus", "Ambient Fields", "ep", "An ambient FlyLo record, which is a sentence worth investigating."),
    ("Khruangbin", "Slow Return", "single", None),
    ("Fred again..", "Actual Life 5", "album", "The next entry in the diary series, and these have not missed yet."),
    ("Denzel Curry", "KING OF THE MISCHIEVOUS SOUTH", "album", None),
    ("The Alchemist", "Flying High", "ep", "A short Alchemist project, which is usually where the strangest beats end up."),
    ("Bibio", "Phantom Brickworks II", "album", None),
    ("Tycho", "Infinite Health", "single", None),
    ("Larry June", "Sunset Boulevard", "album", None),
    ("Blockhead", "Luminous Rooms", "album", "A new Blockhead album is a guaranteed week of instrumentals."),
    ("Disclosure", "Alchemy Sessions", "ep", None),
    ("Emancipator", "River Bend", "single", None),
    ("Westside Gunn", "And Then You Pray for Me II", "album", None),
    ("Nightmares On Wax", "Shape the Future II", "album", "Twenty-odd years in and still the same unhurried touch."),
    ("Four Tet", "Three Twenty", "single", None),
    ("Maribou State", "Hallucinating Love", "album", None),
    ("Viagra Boys", "Cave World II", "album", "Louder and funnier than the last one, which is the correct direction."),
    ("Turnstile", "Never Enough", "album", "The follow-up to the record that took them everywhere."),
    ("Sampha", "Lahai Live", "compilation", None),
    ("Netsky", "Second Nature", "album", None),
    ("High Contrast", "Notes from the Underground", "ep", None),
    ("Calibre", "Feeling Normal", "album", "Calibre releases quietly and often, and the deep ones are always the album tracks."),
    ("Hybrid Minds", "Elements", "single", None),
    ("Steely Dan", "Northeast Corridor Live", "compilation", None),
    ("Dire Straits", "Alchemy Remastered", "compilation", "A remaster of the live record, which is where that band actually lived."),
    ("Grateful Dead", "Dave's Picks Volume 52", "compilation", None),
    ("Fleetwood Mac", "Rumours Live", "compilation", None),
    ("Fontaines D.C.", "Romance", "album", "Fontaines keep getting bigger without getting worse, which almost nobody manages."),
    ("Dry Cleaning", "Stumpwork Sessions", "ep", None),
    ("bar italia", "The Twits", "album", None),
    ("Folamour", "Manifesto", "album", None),
    ("ANOTR", "Relentless", "ep", None),
    ("Joe Goddard", "Harmonics II", "single", None),
    ("Justice", "Hyperdrama Remixes", "compilation", None),
    ("Étienne de Crécy", "Super Discount 4", "album", "The fourth Super Discount, and the formula still filters everything to the bone."),
    ("Cassius", "Dreems Revisited", "compilation", None),
    ("Breakbot", "Remedy", "album", None),
    ("KAYTRANADA", "TIMELESS", "album", "Another long guest list, and the drums are still the reason to show up."),
    ("Robert Glasper", "Black Radio IV", "album", "The series that made jazz musicians comfortable in a studio full of rappers."),
    ("Butcher Brown", "Solar Music II", "album", None),
    ("Yussef Dayes", "Black Classical Music Live", "compilation", None),
    ("Hiatus Kaiyote", "Love Heart Cheat Code", "album", None),
    ("Nujabes", "Metaphorical Music Reissue", "compilation", "A proper reissue at last, and the mastering is finally kind to it."),
    ("MF DOOM", "Operation Doomsday Anniversary", "compilation", None),
    ("Pusha T", "It's Not Dry Yet", "single", None),
    ("Estee Nack", "Nacksaw Jim Duggan", "album", None),
    ("Skrillex", "Fuck U Skrillex", "album", None),
    ("Space Laces", "Overdrive II", "ep", None),
    ("Burial", "Dreamfear", "single", "Burial releases two tracks a year and both are always events."),
    ("Zeds Dead", "Cross the Line", "single", None),
    ("DJ Koze", "Music Can Hear Us", "album", "Koze albums arrive every five years and rearrange the furniture each time."),
    ("Jacques Greene", "Fantasy", "ep", None),
    ("Floating Points", "Cascade", "album", "A neuroscientist making dance music, and the drums are always doing something odd."),
    ("Caribou", "Honey", "album", "Dan Snaith again, still finding new ways to make a sample sound homesick."),
    ("Todd Terje", "Spiral", "single", None),
    ("The Blaze", "Jungle", "album", None),
    ("Jai Paul", "Do You Love Her Now", "single", None),
    ("Yves Tumor", "Praise a Lord Who Bleeds", "album", "Glam rock filtered through something genuinely strange."),
    ("The Donkeys", "Sun Damaged Time", "album", None),
    ("Thievery Corporation", "Symphonik II", "album", None),
    ("The Pharcyde", "Bizarre Ride Live", "compilation", None),
    ("Rebelution", "In the Moment II", "album", "Rebelution put out a record every couple of years and you play all of them."),
    ("Ana Roxanne", "Poem 2", "album", "The sequel to the record that opened one of these issues, and it is just as still."),
    ("Above & Beyond", "Group Therapy Reworked", "compilation", None),
    ("Sub Focus", "Evolve II", "album", "Big-room drum and bass done with real engineering behind it."),
    ("London Elektricity", "Yikes!", "ep", None),
    ("Boards of Canada", "Transmisiones Ferox", "ep", "The first new Boards of Canada material in over a decade."),
    ("The Field", "Sun and Ice", "album", "Loop techno from the man who made it a genre, unchanged and unbothered."),
    ("KOAN Sound", "Polychrome", "ep", None),
    ("Bob Dylan", "Bootleg Series Vol. 18", "compilation", None),
    ("Creedence Clearwater Revival", "At the Royal Albert Hall", "compilation", None),
    ("Griselda", "WWCD II", "album", None),
    ("Tycho", "Weather Patterns", "ep", None),
    ("Bibio", "Sunbursting", "single", None),
    ("Emancipator", "Mountain of Memory", "album", "Downtempo at an eleven-percent skip rate for years, and quiet since the spring."),
    ("Blockhead", "The Aux", "ep", None),
    ("Larry June", "Doing It for Me", "single", None),
    ("Denzel Curry", "Ultimate II", "single", None),
    ("The Alchemist", "Retarded Alligator Beats", "album", None),
    ("Westside Gunn", "Michelle Records", "ep", "Another Gunn project with the Alchemist on most of it, which is the combination that works."),
    ("MF DOOM", "Special Herbs Remastered", "compilation", None),
    ("Four Tet", "Loved", "single", None),
    ("DJ Koze", "Wespennest", "single", None),
    ("Floating Points", "Del Oro", "ep", None),
    ("Khruangbin", "A LA SALA Deluxe", "album", "More from the session that made the last record, and it is the same unhurried room."),
    ("The Blaze", "Territory Reworked", "single", None),
    ("Jai Paul", "He", "single", None),
    ("High Contrast", "The Agony & The Ecstasy II", "album", None),
    ("Calibre", "Shelflife VI", "compilation", "Six volumes of offcuts now, and the offcuts are better than most people's albums."),
    ("Netsky", "Rio", "single", None),
]

# ------------------------------------------------------------ catalogs (11)
# artist, unique_tracks, top3_share, heard, unheard, note
CATALOGS = [
    ("Rebelution", 34, 39, ["Courage to Grow", "Bright Side of Life", "Peace of Mind", "Count Me In"],
     [("In the Moment", 2021), ("Reflections", 2023)],
     "Reggae you already love with most of the shelf still sealed, and the last two records never opened at all."),
    ("Steely Dan", 41, 44, ["Aja", "Peg", "Deacon Blues", "Do It Again"],
     [("Gaucho", 1980), ("The Royal Scam", 1976), ("Countdown to Ecstasy", 1973)],
     "You know the hits and none of the deep cuts, which is backwards for a band whose album tracks are the point."),
    ("Dire Straits", 28, 51, ["Sultans of Swing", "Romeo and Juliet", "Money for Nothing"],
     [("Love Over Gold", 1982), ("On Every Street", 1991)],
     "Four albums heard, two never opened, and the unheard ones are where the long songs live."),
    ("Nujabes", 37, 36, ["Aruarian Dance", "Feather", "Luv(sic) Part 3", "Counting Stars"],
     [("Modal Soul", 2005), ("Spiritual State", 2011)],
     "One producer's whole catalogue is short enough to finish in an afternoon, and you have not."),
    ("Flying Lotus", 52, 31, ["Never Catch Me", "Zodiac Shit", "Putty Boy Strut", "Getting There"],
     [("Until the Quiet Comes", 2012), ("Flamagra", 2019)],
     "The singles get played and the records get skipped, which is the opposite of how he builds them."),
    ("Grateful Dead", 46, 28, ["Eyes of the World", "Sugar Magnolia", "Ripple", "Box of Rain"],
     [("Workingman's Dead", 1970), ("Europe '72", 1972)],
     "A band whose whole argument is the live recordings, and you have only played the studio ones."),
    ("MF DOOM", 58, 33, ["Rapp Snitch Knishes", "Doomsday", "Accordion", "All Caps"],
     [("Vaudeville Villain", 2003), ("Born Like This", 2009)],
     "Every alias is a different record and you have only been playing two of them."),
    ("Disclosure", 31, 47, ["Latch", "You & Me", "White Noise"],
     [("Caracal", 2015), ("Energy", 2020)],
     "The first album lives in your listening and the two after it have never been opened once."),
    ("Fleetwood Mac", 24, 55, ["Gold Dust Woman", "Dreams", "The Chain"],
     [("Tusk", 1979), ("Mirage", 1982)],
     "Rumours is the whole relationship so far, and Tusk is the stranger, better record next to it."),
    ("Bonobo", 43, 34, ["Kiara", "Cirrus", "Kong", "Bambro Koyo Ganda"],
     [("Days to Come", 2006), ("The North Borders", 2013)],
     "You play him constantly and always the same four songs, which he would find funny."),
    ("Khruangbin", 39, 42, ["White Gloves", "August 10", "Friday Morning", "Maria Tambien"],
     [("Con Todo El Mundo", 2018), ("Mordechai", 2020)],
     "The most-played band in your record, and two of their four albums have never been played end to end."),
]


def main():
    cat = json.loads(OUT.read_text())
    cat["singles"] = [{"artist": a, "title": t, "lane": l, "anchor": an, "note": n}
                      for (a, t, l, an, n) in SINGLES]
    cat["mixes"] = [{"show": s, "host": h, "date": d, "lane": l, "tracks_total": tt,
                     "known": k, "anchor": an, "note": n}
                    for (s, h, d, l, tt, k, an, n) in MIXES]
    cat["revivals"] = [{"artist": a, "title": t, "album": al, "plays": p,
                        "last_played": lp, "lane": l, "note": n}
                       for (a, t, al, p, lp, l, n) in REVIVALS]
    cat["releases"] = [{"artist": a, "title": t, "release_type": rt, "note": n}
                       for (a, t, rt, n) in RELEASES]
    cat["catalogs"] = [{"artist": a, "unique_tracks": ut, "top3_share": ts, "heard": hd,
                        "unheard": [{"title": t, "year": y} for (t, y) in uh], "note": n}
                       for (a, ut, ts, hd, uh, n) in CATALOGS]
    OUT.write_text(json.dumps(cat, indent=1, ensure_ascii=False) + "\n")
    print(f"pools filled: {len(cat['singles'])} singles, {len(cat['mixes'])} mixes, "
          f"{len(cat['revivals'])} revivals, {len(cat['releases'])} releases, "
          f"{len(cat['catalogs'])} catalogs")


if __name__ == "__main__":
    main()
